# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainexp.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1751, 877)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(0, 0, 1321, 861))
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.tab_main = QtWidgets.QTabWidget(self.frame_main)
        self.tab_main.setGeometry(QtCore.QRect(10, 10, 801, 711))
        self.tab_main.setObjectName("tab_main")
        self.tab_confocal = QtWidgets.QWidget()
        self.tab_confocal.setObjectName("tab_confocal")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_confocal)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 771, 571))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_confocal = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_confocal.setContentsMargins(0, 0, 0, 0)
        self.grid_confocal.setObjectName("grid_confocal")
        self.btn_confocal_start = QtWidgets.QPushButton(self.tab_confocal)
        self.btn_confocal_start.setGeometry(QtCore.QRect(10, 590, 51, 23))
        self.btn_confocal_start.setObjectName("btn_confocal_start")
        self.btn_confocal_stop = QtWidgets.QPushButton(self.tab_confocal)
        self.btn_confocal_stop.setGeometry(QtCore.QRect(70, 590, 51, 23))
        self.btn_confocal_stop.setObjectName("btn_confocal_stop")
        self.dbl_confocal_x_start = QtWidgets.QDoubleSpinBox(self.tab_confocal)
        self.dbl_confocal_x_start.setGeometry(QtCore.QRect(230, 610, 51, 22))
        self.dbl_confocal_x_start.setObjectName("dbl_confocal_x_start")
        self.dbl_confocal_x_stop = QtWidgets.QDoubleSpinBox(self.tab_confocal)
        self.dbl_confocal_x_stop.setGeometry(QtCore.QRect(230, 630, 51, 22))
        self.dbl_confocal_x_stop.setObjectName("dbl_confocal_x_stop")
        self.int_confocal_x_numdivs = QtWidgets.QSpinBox(self.tab_confocal)
        self.int_confocal_x_numdivs.setGeometry(QtCore.QRect(230, 650, 51, 22))
        self.int_confocal_x_numdivs.setObjectName("int_confocal_x_numdivs")
        self.dbl_confocal_y_start = QtWidgets.QDoubleSpinBox(self.tab_confocal)
        self.dbl_confocal_y_start.setGeometry(QtCore.QRect(290, 610, 51, 22))
        self.dbl_confocal_y_start.setObjectName("dbl_confocal_y_start")
        self.dbl_confocal_y_stop = QtWidgets.QDoubleSpinBox(self.tab_confocal)
        self.dbl_confocal_y_stop.setGeometry(QtCore.QRect(290, 630, 51, 22))
        self.dbl_confocal_y_stop.setObjectName("dbl_confocal_y_stop")
        self.int_confocal_y_numdivs = QtWidgets.QSpinBox(self.tab_confocal)
        self.int_confocal_y_numdivs.setGeometry(QtCore.QRect(290, 650, 51, 22))
        self.int_confocal_y_numdivs.setObjectName("int_confocal_y_numdivs")
        self.dbl_confocal_z_start = QtWidgets.QDoubleSpinBox(self.tab_confocal)
        self.dbl_confocal_z_start.setGeometry(QtCore.QRect(350, 610, 51, 22))
        self.dbl_confocal_z_start.setObjectName("dbl_confocal_z_start")
        self.dbl_confocal_z_stop = QtWidgets.QDoubleSpinBox(self.tab_confocal)
        self.dbl_confocal_z_stop.setGeometry(QtCore.QRect(350, 630, 51, 22))
        self.dbl_confocal_z_stop.setObjectName("dbl_confocal_z_stop")
        self.int_confocal_z_numdivs = QtWidgets.QSpinBox(self.tab_confocal)
        self.int_confocal_z_numdivs.setGeometry(QtCore.QRect(350, 650, 51, 22))
        self.int_confocal_z_numdivs.setObjectName("int_confocal_z_numdivs")
        self.dbl_confocal_acqtime = QtWidgets.QDoubleSpinBox(self.tab_confocal)
        self.dbl_confocal_acqtime.setGeometry(QtCore.QRect(10, 650, 62, 22))
        self.dbl_confocal_acqtime.setObjectName("dbl_confocal_acqtime")
        self.label_confocal_start = QtWidgets.QLabel(self.tab_confocal)
        self.label_confocal_start.setGeometry(QtCore.QRect(180, 610, 47, 22))
        self.label_confocal_start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_confocal_start.setObjectName("label_confocal_start")
        self.label_confocal_stop = QtWidgets.QLabel(self.tab_confocal)
        self.label_confocal_stop.setGeometry(QtCore.QRect(180, 630, 47, 22))
        self.label_confocal_stop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_confocal_stop.setObjectName("label_confocal_stop")
        self.label_confocal_numdivs = QtWidgets.QLabel(self.tab_confocal)
        self.label_confocal_numdivs.setGeometry(QtCore.QRect(180, 650, 47, 22))
        self.label_confocal_numdivs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_confocal_numdivs.setObjectName("label_confocal_numdivs")
        self.label_confocal_x = QtWidgets.QLabel(self.tab_confocal)
        self.label_confocal_x.setGeometry(QtCore.QRect(230, 590, 47, 13))
        self.label_confocal_x.setAlignment(QtCore.Qt.AlignCenter)
        self.label_confocal_x.setObjectName("label_confocal_x")
        self.label_confocal_y = QtWidgets.QLabel(self.tab_confocal)
        self.label_confocal_y.setGeometry(QtCore.QRect(290, 590, 47, 13))
        self.label_confocal_y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_confocal_y.setObjectName("label_confocal_y")
        self.label_confocal_z = QtWidgets.QLabel(self.tab_confocal)
        self.label_confocal_z.setGeometry(QtCore.QRect(350, 590, 47, 13))
        self.label_confocal_z.setAlignment(QtCore.Qt.AlignCenter)
        self.label_confocal_z.setObjectName("label_confocal_z")
        self.label_confocal_acqtime = QtWidgets.QLabel(self.tab_confocal)
        self.label_confocal_acqtime.setGeometry(QtCore.QRect(10, 630, 71, 22))
        self.label_confocal_acqtime.setObjectName("label_confocal_acqtime")
        self.btn_confocal_save = QtWidgets.QPushButton(self.tab_confocal)
        self.btn_confocal_save.setGeometry(QtCore.QRect(130, 590, 51, 23))
        self.btn_confocal_save.setObjectName("btn_confocal_save")
        self.btn_confocal_autoZ = QtWidgets.QPushButton(self.tab_confocal)
        self.btn_confocal_autoZ.setGeometry(QtCore.QRect(410, 650, 51, 23))
        self.btn_confocal_autoZ.setCheckable(True)
        self.btn_confocal_autoZ.setObjectName("btn_confocal_autoZ")
        self.btn_confocal_mode_xy = QtWidgets.QRadioButton(self.tab_confocal)
        self.btn_confocal_mode_xy.setGeometry(QtCore.QRect(480, 610, 71, 17))
        self.btn_confocal_mode_xy.setObjectName("btn_confocal_mode_xy")
        self.btn_confocal_mode_xz = QtWidgets.QRadioButton(self.tab_confocal)
        self.btn_confocal_mode_xz.setGeometry(QtCore.QRect(480, 630, 71, 17))
        self.btn_confocal_mode_xz.setObjectName("btn_confocal_mode_xz")
        self.btn_confocal_mode_yz = QtWidgets.QRadioButton(self.tab_confocal)
        self.btn_confocal_mode_yz.setGeometry(QtCore.QRect(480, 650, 71, 17))
        self.btn_confocal_mode_yz.setObjectName("btn_confocal_mode_yz")
        self.chkbx_confocal_autolevel = QtWidgets.QCheckBox(self.tab_confocal)
        self.chkbx_confocal_autolevel.setGeometry(QtCore.QRect(710, 590, 70, 17))
        self.chkbx_confocal_autolevel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkbx_confocal_autolevel.setObjectName("chkbx_confocal_autolevel")
        self.dbl_confocal_stage_x = QtWidgets.QDoubleSpinBox(self.tab_confocal)
        self.dbl_confocal_stage_x.setGeometry(QtCore.QRect(620, 610, 62, 22))
        self.dbl_confocal_stage_x.setObjectName("dbl_confocal_stage_x")
        self.dbl_confocal_stage_y = QtWidgets.QDoubleSpinBox(self.tab_confocal)
        self.dbl_confocal_stage_y.setGeometry(QtCore.QRect(620, 630, 62, 22))
        self.dbl_confocal_stage_y.setObjectName("dbl_confocal_stage_y")
        self.label_stage_x = QtWidgets.QLabel(self.tab_confocal)
        self.label_stage_x.setGeometry(QtCore.QRect(570, 610, 47, 22))
        self.label_stage_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_stage_x.setObjectName("label_stage_x")
        self.label_stage_y = QtWidgets.QLabel(self.tab_confocal)
        self.label_stage_y.setGeometry(QtCore.QRect(570, 630, 47, 22))
        self.label_stage_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_stage_y.setObjectName("label_stage_y")
        self.chkbx_confocal_esr = QtWidgets.QCheckBox(self.tab_confocal)
        self.chkbx_confocal_esr.setGeometry(QtCore.QRect(630, 660, 151, 17))
        self.chkbx_confocal_esr.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkbx_confocal_esr.setObjectName("chkbx_confocal_esr")
        self.btn_confocal_live = QtWidgets.QPushButton(self.tab_confocal)
        self.btn_confocal_live.setGeometry(QtCore.QRect(130, 650, 51, 22))
        self.btn_confocal_live.setCheckable(True)
        self.btn_confocal_live.setObjectName("btn_confocal_live")
        self.label_confocal_live_avg = QtWidgets.QLabel(self.tab_confocal)
        self.label_confocal_live_avg.setGeometry(QtCore.QRect(80, 630, 31, 22))
        self.label_confocal_live_avg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_confocal_live_avg.setObjectName("label_confocal_live_avg")
        self.int_confocal_live_avg = QtWidgets.QSpinBox(self.tab_confocal)
        self.int_confocal_live_avg.setGeometry(QtCore.QRect(80, 650, 51, 22))
        self.int_confocal_live_avg.setKeyboardTracking(False)
        self.int_confocal_live_avg.setObjectName("int_confocal_live_avg")
        self.tab_main.addTab(self.tab_confocal, "")
        self.tab_exp = QtWidgets.QWidget()
        self.tab_exp.setObjectName("tab_exp")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_exp)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 380, 511, 251))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.grid_data_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.grid_data_2.setContentsMargins(0, 0, 0, 0)
        self.grid_data_2.setObjectName("grid_data_2")
        self.tree_exp_params = QtWidgets.QTreeView(self.tab_exp)
        self.tree_exp_params.setGeometry(QtCore.QRect(530, 10, 256, 671))
        self.tree_exp_params.setObjectName("tree_exp_params")
        self.var1_name = QtWidgets.QComboBox(self.tab_exp)
        self.var1_name.setGeometry(QtCore.QRect(40, 320, 121, 22))
        self.var1_name.setObjectName("var1_name")
        self.var1_start = QtWidgets.QDoubleSpinBox(self.tab_exp)
        self.var1_start.setGeometry(QtCore.QRect(170, 320, 71, 22))
        self.var1_start.setObjectName("var1_start")
        self.var1_start_unit = QtWidgets.QComboBox(self.tab_exp)
        self.var1_start_unit.setGeometry(QtCore.QRect(240, 320, 31, 22))
        self.var1_start_unit.setObjectName("var1_start_unit")
        self.var1_stop = QtWidgets.QDoubleSpinBox(self.tab_exp)
        self.var1_stop.setGeometry(QtCore.QRect(280, 320, 71, 22))
        self.var1_stop.setObjectName("var1_stop")
        self.var1_stop_unit = QtWidgets.QComboBox(self.tab_exp)
        self.var1_stop_unit.setGeometry(QtCore.QRect(350, 320, 31, 22))
        self.var1_stop_unit.setObjectName("var1_stop_unit")
        self.var1_numdivs = QtWidgets.QSpinBox(self.tab_exp)
        self.var1_numdivs.setGeometry(QtCore.QRect(390, 320, 51, 22))
        self.var1_numdivs.setObjectName("var1_numdivs")
        self.var1_delay = QtWidgets.QDoubleSpinBox(self.tab_exp)
        self.var1_delay.setGeometry(QtCore.QRect(440, 320, 62, 22))
        self.var1_delay.setObjectName("var1_delay")
        self.chkbx_2dexp = QtWidgets.QCheckBox(self.tab_exp)
        self.chkbx_2dexp.setGeometry(QtCore.QRect(10, 350, 21, 22))
        self.chkbx_2dexp.setText("")
        self.chkbx_2dexp.setObjectName("chkbx_2dexp")
        self.var2_name = QtWidgets.QComboBox(self.tab_exp)
        self.var2_name.setGeometry(QtCore.QRect(40, 350, 121, 22))
        self.var2_name.setObjectName("var2_name")
        self.var2_start = QtWidgets.QDoubleSpinBox(self.tab_exp)
        self.var2_start.setGeometry(QtCore.QRect(170, 350, 71, 22))
        self.var2_start.setObjectName("var2_start")
        self.var2_start_unit = QtWidgets.QComboBox(self.tab_exp)
        self.var2_start_unit.setGeometry(QtCore.QRect(240, 350, 31, 22))
        self.var2_start_unit.setObjectName("var2_start_unit")
        self.var2_stop = QtWidgets.QDoubleSpinBox(self.tab_exp)
        self.var2_stop.setGeometry(QtCore.QRect(280, 350, 71, 22))
        self.var2_stop.setObjectName("var2_stop")
        self.var2_stop_unit = QtWidgets.QComboBox(self.tab_exp)
        self.var2_stop_unit.setGeometry(QtCore.QRect(350, 350, 31, 22))
        self.var2_stop_unit.setObjectName("var2_stop_unit")
        self.var2_numdivs = QtWidgets.QSpinBox(self.tab_exp)
        self.var2_numdivs.setGeometry(QtCore.QRect(390, 350, 51, 22))
        self.var2_numdivs.setObjectName("var2_numdivs")
        self.var2_delay = QtWidgets.QDoubleSpinBox(self.tab_exp)
        self.var2_delay.setGeometry(QtCore.QRect(440, 350, 62, 22))
        self.var2_delay.setObjectName("var2_delay")
        self.btn_exp_start = QtWidgets.QPushButton(self.tab_exp)
        self.btn_exp_start.setGeometry(QtCore.QRect(400, 660, 61, 23))
        self.btn_exp_start.setObjectName("btn_exp_start")
        self.btn_exp_stop = QtWidgets.QPushButton(self.tab_exp)
        self.btn_exp_stop.setGeometry(QtCore.QRect(460, 660, 61, 23))
        self.btn_exp_stop.setObjectName("btn_exp_stop")
        self.btn_swap_var = QtWidgets.QPushButton(self.tab_exp)
        self.btn_swap_var.setGeometry(QtCore.QRect(510, 330, 16, 31))
        self.btn_swap_var.setObjectName("btn_swap_var")
        self.chkbx_exp_logx = QtWidgets.QCheckBox(self.tab_exp)
        self.chkbx_exp_logx.setGeometry(QtCore.QRect(480, 300, 41, 13))
        self.chkbx_exp_logx.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkbx_exp_logx.setObjectName("chkbx_exp_logx")
        self.chkbx_exp_autofit = QtWidgets.QCheckBox(self.tab_exp)
        self.chkbx_exp_autofit.setGeometry(QtCore.QRect(10, 660, 41, 23))
        self.chkbx_exp_autofit.setObjectName("chkbx_exp_autofit")
        self.cbox_fittype = QtWidgets.QComboBox(self.tab_exp)
        self.cbox_fittype.setGeometry(QtCore.QRect(50, 660, 121, 23))
        self.cbox_fittype.setObjectName("cbox_fittype")
        self.label_exp_var_name = QtWidgets.QLabel(self.tab_exp)
        self.label_exp_var_name.setGeometry(QtCore.QRect(40, 300, 81, 13))
        self.label_exp_var_name.setObjectName("label_exp_var_name")
        self.label_exp_var_start = QtWidgets.QLabel(self.tab_exp)
        self.label_exp_var_start.setGeometry(QtCore.QRect(170, 300, 46, 13))
        self.label_exp_var_start.setObjectName("label_exp_var_start")
        self.label_exp_var_stop = QtWidgets.QLabel(self.tab_exp)
        self.label_exp_var_stop.setGeometry(QtCore.QRect(280, 300, 46, 13))
        self.label_exp_var_stop.setObjectName("label_exp_var_stop")
        self.label_exp_var_numdivs = QtWidgets.QLabel(self.tab_exp)
        self.label_exp_var_numdivs.setGeometry(QtCore.QRect(390, 300, 46, 13))
        self.label_exp_var_numdivs.setObjectName("label_exp_var_numdivs")
        self.label_exp_var_delay = QtWidgets.QLabel(self.tab_exp)
        self.label_exp_var_delay.setGeometry(QtCore.QRect(440, 300, 46, 13))
        self.label_exp_var_delay.setObjectName("label_exp_var_delay")
        self.label_exp_var1 = QtWidgets.QLabel(self.tab_exp)
        self.label_exp_var1.setGeometry(QtCore.QRect(20, 320, 16, 22))
        self.label_exp_var1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_exp_var1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_exp_var1.setObjectName("label_exp_var1")
        self.label_exp_var2 = QtWidgets.QLabel(self.tab_exp)
        self.label_exp_var2.setGeometry(QtCore.QRect(20, 350, 16, 22))
        self.label_exp_var2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_exp_var2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_exp_var2.setObjectName("label_exp_var2")
        self.chkbx_beep = QtWidgets.QCheckBox(self.tab_exp)
        self.chkbx_beep.setGeometry(QtCore.QRect(290, 660, 101, 23))
        self.chkbx_beep.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkbx_beep.setObjectName("chkbx_beep")
        self.btn_exp_save = QtWidgets.QPushButton(self.tab_exp)
        self.btn_exp_save.setGeometry(QtCore.QRect(230, 660, 61, 23))
        self.btn_exp_save.setObjectName("btn_exp_save")
        self.chkbx_2dexp_meander = QtWidgets.QCheckBox(self.tab_exp)
        self.chkbx_2dexp_meander.setGeometry(QtCore.QRect(10, 635, 71, 17))
        self.chkbx_2dexp_meander.setObjectName("chkbx_2dexp_meander")
        self.chkbx_PLE_fast = QtWidgets.QCheckBox(self.tab_exp)
        self.chkbx_PLE_fast.setGeometry(QtCore.QRect(80, 635, 101, 17))
        self.chkbx_PLE_fast.setObjectName("chkbx_PLE_fast")
        self.chkbx_newctr_2d = QtWidgets.QCheckBox(self.tab_exp)
        self.chkbx_newctr_2d.setGeometry(QtCore.QRect(180, 635, 101, 17))
        self.chkbx_newctr_2d.setObjectName("chkbx_newctr_2d")
        self.frame_exp_fig = QtWidgets.QFrame(self.tab_exp)
        self.frame_exp_fig.setGeometry(QtCore.QRect(10, 10, 511, 281))
        self.frame_exp_fig.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_exp_fig.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_exp_fig.setObjectName("frame_exp_fig")
        self.label_filename = QtWidgets.QLabel(self.frame_exp_fig)
        self.label_filename.setGeometry(QtCore.QRect(280, 0, 231, 22))
        self.label_filename.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filename.setObjectName("label_filename")
        self.label_nvlist = QtWidgets.QLabel(self.frame_exp_fig)
        self.label_nvlist.setGeometry(QtCore.QRect(190, 0, 81, 22))
        self.label_nvlist.setObjectName("label_nvlist")
        self.cbox_exp_name = QtWidgets.QComboBox(self.frame_exp_fig)
        self.cbox_exp_name.setGeometry(QtCore.QRect(30, 0, 141, 22))
        self.cbox_exp_name.setObjectName("cbox_exp_name")
        self.label_exp_name = QtWidgets.QLabel(self.frame_exp_fig)
        self.label_exp_name.setGeometry(QtCore.QRect(0, 0, 31, 22))
        self.label_exp_name.setObjectName("label_exp_name")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame_exp_fig)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 30, 511, 251))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.grid_data_1 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.grid_data_1.setContentsMargins(0, 0, 0, 0)
        self.grid_data_1.setObjectName("grid_data_1")
        self.label_exp_pause = QtWidgets.QLabel(self.frame_exp_fig)
        self.label_exp_pause.setGeometry(QtCore.QRect(140, 100, 241, 21))
        self.label_exp_pause.setAutoFillBackground(True)
        self.label_exp_pause.setObjectName("label_exp_pause")
        self.btn_exp_pause = QtWidgets.QPushButton(self.frame_exp_fig)
        self.btn_exp_pause.setGeometry(QtCore.QRect(210, 140, 75, 23))
        self.btn_exp_pause.setAutoFillBackground(False)
        self.btn_exp_pause.setObjectName("btn_exp_pause")
        self.label_exp_params = QtWidgets.QLabel(self.frame_exp_fig)
        self.label_exp_params.setGeometry(QtCore.QRect(310, 30, 201, 161))
        self.label_exp_params.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_exp_params.setWordWrap(True)
        self.label_exp_params.setObjectName("label_exp_params")
        self.btn_exp_fit = QtWidgets.QPushButton(self.tab_exp)
        self.btn_exp_fit.setGeometry(QtCore.QRect(170, 660, 61, 23))
        self.btn_exp_fit.setObjectName("btn_exp_fit")
        self.tab_main.addTab(self.tab_exp, "")
        self.tab_spectrometer = QtWidgets.QWidget()
        self.tab_spectrometer.setObjectName("tab_spectrometer")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.tab_spectrometer)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(10, 30, 771, 551))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.grid_spectrometer = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.grid_spectrometer.setContentsMargins(0, 0, 0, 0)
        self.grid_spectrometer.setObjectName("grid_spectrometer")
        self.dbl_spectrometer_centerwavelength = QtWidgets.QDoubleSpinBox(self.tab_spectrometer)
        self.dbl_spectrometer_centerwavelength.setGeometry(QtCore.QRect(280, 610, 71, 23))
        self.dbl_spectrometer_centerwavelength.setKeyboardTracking(False)
        self.dbl_spectrometer_centerwavelength.setMaximum(1100.0)
        self.dbl_spectrometer_centerwavelength.setSingleStep(5.0)
        self.dbl_spectrometer_centerwavelength.setObjectName("dbl_spectrometer_centerwavelength")
        self.dbl_spectrometer_exptime = QtWidgets.QDoubleSpinBox(self.tab_spectrometer)
        self.dbl_spectrometer_exptime.setGeometry(QtCore.QRect(280, 640, 71, 23))
        self.dbl_spectrometer_exptime.setMaximum(999999.0)
        self.dbl_spectrometer_exptime.setObjectName("dbl_spectrometer_exptime")
        self.int_spectrometer_xbin_start = QtWidgets.QSpinBox(self.tab_spectrometer)
        self.int_spectrometer_xbin_start.setGeometry(QtCore.QRect(430, 610, 51, 23))
        self.int_spectrometer_xbin_start.setMaximum(1350)
        self.int_spectrometer_xbin_start.setObjectName("int_spectrometer_xbin_start")
        self.int_spectrometer_xbin_stop = QtWidgets.QSpinBox(self.tab_spectrometer)
        self.int_spectrometer_xbin_stop.setGeometry(QtCore.QRect(430, 640, 51, 23))
        self.int_spectrometer_xbin_stop.setMaximum(1340)
        self.int_spectrometer_xbin_stop.setObjectName("int_spectrometer_xbin_stop")
        self.chkbx_spectrometer_xbin = QtWidgets.QCheckBox(self.tab_spectrometer)
        self.chkbx_spectrometer_xbin.setGeometry(QtCore.QRect(410, 665, 71, 17))
        self.chkbx_spectrometer_xbin.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkbx_spectrometer_xbin.setObjectName("chkbx_spectrometer_xbin")
        self.int_spectrometer_ybin_start = QtWidgets.QSpinBox(self.tab_spectrometer)
        self.int_spectrometer_ybin_start.setGeometry(QtCore.QRect(510, 610, 51, 23))
        self.int_spectrometer_ybin_start.setMaximum(100)
        self.int_spectrometer_ybin_start.setObjectName("int_spectrometer_ybin_start")
        self.int_spectrometer_ybin_stop = QtWidgets.QSpinBox(self.tab_spectrometer)
        self.int_spectrometer_ybin_stop.setGeometry(QtCore.QRect(510, 640, 51, 23))
        self.int_spectrometer_ybin_stop.setMaximum(100)
        self.int_spectrometer_ybin_stop.setObjectName("int_spectrometer_ybin_stop")
        self.chkbx_spectrometer_ybin = QtWidgets.QCheckBox(self.tab_spectrometer)
        self.chkbx_spectrometer_ybin.setGeometry(QtCore.QRect(490, 665, 71, 17))
        self.chkbx_spectrometer_ybin.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkbx_spectrometer_ybin.setObjectName("chkbx_spectrometer_ybin")
        self.btn_spectrometer_acquire = QtWidgets.QPushButton(self.tab_spectrometer)
        self.btn_spectrometer_acquire.setGeometry(QtCore.QRect(10, 610, 51, 23))
        self.btn_spectrometer_acquire.setObjectName("btn_spectrometer_acquire")
        self.btn_spectrometer_stop = QtWidgets.QPushButton(self.tab_spectrometer)
        self.btn_spectrometer_stop.setGeometry(QtCore.QRect(70, 610, 51, 23))
        self.btn_spectrometer_stop.setObjectName("btn_spectrometer_stop")
        self.label_spectrometer_centerwavelength = QtWidgets.QLabel(self.tab_spectrometer)
        self.label_spectrometer_centerwavelength.setGeometry(QtCore.QRect(140, 610, 131, 23))
        self.label_spectrometer_centerwavelength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_spectrometer_centerwavelength.setObjectName("label_spectrometer_centerwavelength")
        self.label_spectrometer_exptime = QtWidgets.QLabel(self.tab_spectrometer)
        self.label_spectrometer_exptime.setGeometry(QtCore.QRect(180, 640, 91, 23))
        self.label_spectrometer_exptime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_spectrometer_exptime.setObjectName("label_spectrometer_exptime")
        self.label_spectrometer_xbin = QtWidgets.QLabel(self.tab_spectrometer)
        self.label_spectrometer_xbin.setGeometry(QtCore.QRect(430, 590, 51, 16))
        self.label_spectrometer_xbin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spectrometer_xbin.setObjectName("label_spectrometer_xbin")
        self.label_spectrometer_ybin = QtWidgets.QLabel(self.tab_spectrometer)
        self.label_spectrometer_ybin.setGeometry(QtCore.QRect(510, 590, 51, 16))
        self.label_spectrometer_ybin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spectrometer_ybin.setObjectName("label_spectrometer_ybin")
        self.label_nvlist_spectrometer = QtWidgets.QLabel(self.tab_spectrometer)
        self.label_nvlist_spectrometer.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label_nvlist_spectrometer.setObjectName("label_nvlist_spectrometer")
        self.label_spectrometer_start = QtWidgets.QLabel(self.tab_spectrometer)
        self.label_spectrometer_start.setGeometry(QtCore.QRect(390, 610, 31, 23))
        self.label_spectrometer_start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_spectrometer_start.setObjectName("label_spectrometer_start")
        self.label_spectrometer_start_2 = QtWidgets.QLabel(self.tab_spectrometer)
        self.label_spectrometer_start_2.setGeometry(QtCore.QRect(390, 640, 31, 23))
        self.label_spectrometer_start_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_spectrometer_start_2.setObjectName("label_spectrometer_start_2")
        self.btn_spectrometer_save = QtWidgets.QPushButton(self.tab_spectrometer)
        self.btn_spectrometer_save.setGeometry(QtCore.QRect(70, 640, 51, 23))
        self.btn_spectrometer_save.setObjectName("btn_spectrometer_save")
        self.label_spectrometer_temp = QtWidgets.QLabel(self.tab_spectrometer)
        self.label_spectrometer_temp.setGeometry(QtCore.QRect(650, 610, 131, 23))
        self.label_spectrometer_temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_spectrometer_temp.setObjectName("label_spectrometer_temp")
        self.cbox_spectrometer_grating = QtWidgets.QComboBox(self.tab_spectrometer)
        self.cbox_spectrometer_grating.setGeometry(QtCore.QRect(600, 640, 181, 22))
        self.cbox_spectrometer_grating.setObjectName("cbox_spectrometer_grating")
        self.btn_spectrometer_live = QtWidgets.QPushButton(self.tab_spectrometer)
        self.btn_spectrometer_live.setGeometry(QtCore.QRect(10, 640, 51, 23))
        self.btn_spectrometer_live.setCheckable(True)
        self.btn_spectrometer_live.setObjectName("btn_spectrometer_live")
        self.btn_spectrometer_connect = QtWidgets.QPushButton(self.tab_spectrometer)
        self.btn_spectrometer_connect.setGeometry(QtCore.QRect(600, 610, 51, 23))
        self.btn_spectrometer_connect.setCheckable(True)
        self.btn_spectrometer_connect.setObjectName("btn_spectrometer_connect")
        self.tab_main.addTab(self.tab_spectrometer, "")
        self.linein_sample_name = QtWidgets.QLineEdit(self.frame_main)
        self.linein_sample_name.setGeometry(QtCore.QRect(630, 10, 181, 20))
        self.linein_sample_name.setPlaceholderText("")
        self.linein_sample_name.setObjectName("linein_sample_name")
        self.label_sample_name = QtWidgets.QLabel(self.frame_main)
        self.label_sample_name.setGeometry(QtCore.QRect(588, 10, 47, 13))
        self.label_sample_name.setObjectName("label_sample_name")
        self.chkbx_autosave = QtWidgets.QCheckBox(self.frame_main)
        self.chkbx_autosave.setGeometry(QtCore.QRect(10, 750, 81, 17))
        self.chkbx_autosave.setObjectName("chkbx_autosave")
        self.label_p532 = QtWidgets.QLabel(self.frame_main)
        self.label_p532.setGeometry(QtCore.QRect(10, 730, 161, 16))
        self.label_p532.setObjectName("label_p532")
        self.groupBox_logdisp = QtWidgets.QGroupBox(self.frame_main)
        self.groupBox_logdisp.setGeometry(QtCore.QRect(370, 730, 441, 121))
        self.groupBox_logdisp.setObjectName("groupBox_logdisp")
        self.logdisp_scroll = QtWidgets.QScrollArea(self.groupBox_logdisp)
        self.logdisp_scroll.setGeometry(QtCore.QRect(10, 20, 421, 91))
        self.logdisp_scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.logdisp_scroll.setWidgetResizable(True)
        self.logdisp_scroll.setObjectName("logdisp_scroll")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 419, 89))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.logdisp = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.logdisp.setGeometry(QtCore.QRect(0, 0, 421, 91))
        self.logdisp.setObjectName("logdisp")
        self.logdisp_scroll.setWidget(self.scrollAreaWidgetContents_2)
        self.groupBox_confocal = QtWidgets.QGroupBox(self.frame_main)
        self.groupBox_confocal.setGeometry(QtCore.QRect(830, 10, 471, 441))
        self.groupBox_confocal.setObjectName("groupBox_confocal")
        self.linein_map = QtWidgets.QLabel(self.groupBox_confocal)
        self.linein_map.setGeometry(QtCore.QRect(10, 20, 181, 20))
        self.linein_map.setObjectName("linein_map")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_confocal)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 50, 451, 381))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.grid_map = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.grid_map.setContentsMargins(0, 0, 0, 0)
        self.grid_map.setObjectName("grid_map")
        self.btn_map_load = QtWidgets.QPushButton(self.groupBox_confocal)
        self.btn_map_load.setGeometry(QtCore.QRect(310, 20, 51, 23))
        self.btn_map_load.setObjectName("btn_map_load")
        self.btn_map_copy = QtWidgets.QPushButton(self.groupBox_confocal)
        self.btn_map_copy.setGeometry(QtCore.QRect(360, 20, 51, 23))
        self.btn_map_copy.setObjectName("btn_map_copy")
        self.btn_map_select = QtWidgets.QPushButton(self.groupBox_confocal)
        self.btn_map_select.setGeometry(QtCore.QRect(410, 20, 51, 23))
        self.btn_map_select.setCheckable(True)
        self.btn_map_select.setObjectName("btn_map_select")
        self.groupBox_expinfo = QtWidgets.QGroupBox(self.frame_main)
        self.groupBox_expinfo.setGeometry(QtCore.QRect(830, 460, 471, 391))
        self.groupBox_expinfo.setObjectName("groupBox_expinfo")
        self.label_pb_disp = QtWidgets.QLabel(self.groupBox_expinfo)
        self.label_pb_disp.setGeometry(QtCore.QRect(35, 0, 401, 201))
        self.label_pb_disp.setText("")
        self.label_pb_disp.setObjectName("label_pb_disp")
        self.groupBox_modules = QtWidgets.QGroupBox(self.groupBox_expinfo)
        self.groupBox_modules.setGeometry(QtCore.QRect(10, 170, 171, 121))
        self.groupBox_modules.setObjectName("groupBox_modules")
        self.btn_widget_liveapd = QtWidgets.QPushButton(self.groupBox_modules)
        self.btn_widget_liveapd.setGeometry(QtCore.QRect(10, 15, 75, 23))
        self.btn_widget_liveapd.setCheckable(True)
        self.btn_widget_liveapd.setObjectName("btn_widget_liveapd")
        self.btn_widget_seqapd = QtWidgets.QPushButton(self.groupBox_modules)
        self.btn_widget_seqapd.setGeometry(QtCore.QRect(90, 15, 75, 23))
        self.btn_widget_seqapd.setCheckable(True)
        self.btn_widget_seqapd.setObjectName("btn_widget_seqapd")
        self.btn_widget_satcurve = QtWidgets.QPushButton(self.groupBox_modules)
        self.btn_widget_satcurve.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.btn_widget_satcurve.setCheckable(True)
        self.btn_widget_satcurve.setObjectName("btn_widget_satcurve")
        self.btn_widget_histogram = QtWidgets.QPushButton(self.groupBox_modules)
        self.btn_widget_histogram.setGeometry(QtCore.QRect(90, 40, 75, 23))
        self.btn_widget_histogram.setCheckable(True)
        self.btn_widget_histogram.setObjectName("btn_widget_histogram")
        self.btn_widget_picoharp = QtWidgets.QPushButton(self.groupBox_modules)
        self.btn_widget_picoharp.setGeometry(QtCore.QRect(10, 65, 75, 23))
        self.btn_widget_picoharp.setCheckable(True)
        self.btn_widget_picoharp.setObjectName("btn_widget_picoharp")
        self.btn_widget_calculator = QtWidgets.QPushButton(self.groupBox_modules)
        self.btn_widget_calculator.setGeometry(QtCore.QRect(90, 65, 75, 23))
        self.btn_widget_calculator.setCheckable(True)
        self.btn_widget_calculator.setObjectName("btn_widget_calculator")
        self.btn_widget_batch = QtWidgets.QPushButton(self.groupBox_modules)
        self.btn_widget_batch.setGeometry(QtCore.QRect(10, 90, 75, 23))
        self.btn_widget_batch.setCheckable(True)
        self.btn_widget_batch.setObjectName("btn_widget_batch")
        self.btn_widget_terminal = QtWidgets.QPushButton(self.groupBox_modules)
        self.btn_widget_terminal.setGeometry(QtCore.QRect(90, 90, 75, 23))
        self.btn_widget_terminal.setCheckable(True)
        self.btn_widget_terminal.setObjectName("btn_widget_terminal")
        self.groupBox_plnorm = QtWidgets.QGroupBox(self.groupBox_expinfo)
        self.groupBox_plnorm.setGeometry(QtCore.QRect(10, 290, 131, 91))
        self.groupBox_plnorm.setObjectName("groupBox_plnorm")
        self.dbl_plnorm_bright = QtWidgets.QDoubleSpinBox(self.groupBox_plnorm)
        self.dbl_plnorm_bright.setGeometry(QtCore.QRect(60, 20, 51, 22))
        self.dbl_plnorm_bright.setSpecialValueText("")
        self.dbl_plnorm_bright.setDecimals(3)
        self.dbl_plnorm_bright.setObjectName("dbl_plnorm_bright")
        self.dbl_plnorm_dark = QtWidgets.QDoubleSpinBox(self.groupBox_plnorm)
        self.dbl_plnorm_dark.setGeometry(QtCore.QRect(60, 40, 51, 22))
        self.dbl_plnorm_dark.setDecimals(3)
        self.dbl_plnorm_dark.setObjectName("dbl_plnorm_dark")
        self.label_plnorm_bright = QtWidgets.QLabel(self.groupBox_plnorm)
        self.label_plnorm_bright.setGeometry(QtCore.QRect(10, 20, 61, 22))
        self.label_plnorm_bright.setObjectName("label_plnorm_bright")
        self.label_plnorm_dark = QtWidgets.QLabel(self.groupBox_plnorm)
        self.label_plnorm_dark.setGeometry(QtCore.QRect(10, 40, 61, 22))
        self.label_plnorm_dark.setObjectName("label_plnorm_dark")
        self.chkbx_plnorm = QtWidgets.QCheckBox(self.groupBox_plnorm)
        self.chkbx_plnorm.setGeometry(QtCore.QRect(10, 65, 101, 17))
        self.chkbx_plnorm.setObjectName("chkbx_plnorm")
        self.groupBox_fits = QtWidgets.QGroupBox(self.groupBox_expinfo)
        self.groupBox_fits.setGeometry(QtCore.QRect(190, 210, 271, 171))
        self.groupBox_fits.setObjectName("groupBox_fits")
        self.disp_fits = QtWidgets.QTextBrowser(self.groupBox_fits)
        self.disp_fits.setGeometry(QtCore.QRect(10, 20, 251, 141))
        self.disp_fits.setObjectName("disp_fits")
        self.chkbx_row_timings = QtWidgets.QCheckBox(self.groupBox_expinfo)
        self.chkbx_row_timings.setGeometry(QtCore.QRect(250, 170, 111, 17))
        self.chkbx_row_timings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbx_row_timings.setObjectName("chkbx_row_timings")
        self.chkbx_readoutcal = QtWidgets.QCheckBox(self.groupBox_expinfo)
        self.chkbx_readoutcal.setGeometry(QtCore.QRect(250, 190, 111, 17))
        self.chkbx_readoutcal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbx_readoutcal.setObjectName("chkbx_readoutcal")
        self.chkbx_inv2 = QtWidgets.QCheckBox(self.groupBox_expinfo)
        self.chkbx_inv2.setGeometry(QtCore.QRect(370, 170, 91, 17))
        self.chkbx_inv2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbx_inv2.setObjectName("chkbx_inv2")
        self.chkbx_inv = QtWidgets.QCheckBox(self.groupBox_expinfo)
        self.chkbx_inv.setGeometry(QtCore.QRect(370, 190, 91, 17))
        self.chkbx_inv.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbx_inv.setObjectName("chkbx_inv")
        self.label_sweep_time_est = QtWidgets.QLabel(self.frame_main)
        self.label_sweep_time_est.setGeometry(QtCore.QRect(10, 820, 351, 16))
        self.label_sweep_time_est.setObjectName("label_sweep_time_est")
        self.groupBox = QtWidgets.QGroupBox(self.frame_main)
        self.groupBox.setGeometry(QtCore.QRect(160, 730, 201, 121))
        self.groupBox.setObjectName("groupBox")
        self.btn_shortcuts_1 = QtWidgets.QPushButton(self.groupBox)
        self.btn_shortcuts_1.setGeometry(QtCore.QRect(10, 30, 91, 23))
        self.btn_shortcuts_1.setText("")
        self.btn_shortcuts_1.setObjectName("btn_shortcuts_1")
        self.btn_shortcuts_2 = QtWidgets.QPushButton(self.groupBox)
        self.btn_shortcuts_2.setGeometry(QtCore.QRect(10, 50, 91, 23))
        self.btn_shortcuts_2.setText("")
        self.btn_shortcuts_2.setObjectName("btn_shortcuts_2")
        self.btn_shortcuts_3 = QtWidgets.QPushButton(self.groupBox)
        self.btn_shortcuts_3.setGeometry(QtCore.QRect(10, 70, 91, 23))
        self.btn_shortcuts_3.setText("")
        self.btn_shortcuts_3.setObjectName("btn_shortcuts_3")
        self.btn_shortcuts_4 = QtWidgets.QPushButton(self.groupBox)
        self.btn_shortcuts_4.setGeometry(QtCore.QRect(10, 90, 91, 23))
        self.btn_shortcuts_4.setText("")
        self.btn_shortcuts_4.setObjectName("btn_shortcuts_4")
        self.btn_shortcuts_5 = QtWidgets.QPushButton(self.groupBox)
        self.btn_shortcuts_5.setGeometry(QtCore.QRect(100, 30, 91, 23))
        self.btn_shortcuts_5.setText("")
        self.btn_shortcuts_5.setObjectName("btn_shortcuts_5")
        self.btn_shortcuts_6 = QtWidgets.QPushButton(self.groupBox)
        self.btn_shortcuts_6.setGeometry(QtCore.QRect(100, 50, 91, 23))
        self.btn_shortcuts_6.setText("")
        self.btn_shortcuts_6.setObjectName("btn_shortcuts_6")
        self.btn_shortcuts_7 = QtWidgets.QPushButton(self.groupBox)
        self.btn_shortcuts_7.setGeometry(QtCore.QRect(100, 70, 91, 23))
        self.btn_shortcuts_7.setText("")
        self.btn_shortcuts_7.setObjectName("btn_shortcuts_7")
        self.btn_shortcuts_8 = QtWidgets.QPushButton(self.groupBox)
        self.btn_shortcuts_8.setGeometry(QtCore.QRect(100, 90, 91, 23))
        self.btn_shortcuts_8.setText("")
        self.btn_shortcuts_8.setObjectName("btn_shortcuts_8")
        self.btn_widget_shortcuts = QtWidgets.QPushButton(self.groupBox)
        self.btn_widget_shortcuts.setGeometry(QtCore.QRect(160, 10, 31, 23))
        self.btn_widget_shortcuts.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/gears.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_widget_shortcuts.setIcon(icon)
        self.btn_widget_shortcuts.setCheckable(True)
        self.btn_widget_shortcuts.setObjectName("btn_widget_shortcuts")
        self.frame_toolbox = QtWidgets.QFrame(self.centralwidget)
        self.frame_toolbox.setGeometry(QtCore.QRect(1320, -1, 431, 861))
        self.frame_toolbox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toolbox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toolbox.setObjectName("frame_toolbox")
        self.tab_toolbox = QtWidgets.QTabWidget(self.frame_toolbox)
        self.tab_toolbox.setGeometry(QtCore.QRect(0, 10, 425, 841))
        self.tab_toolbox.setObjectName("tab_toolbox")
        self.tab_tracker = QtWidgets.QWidget()
        self.tab_tracker.setObjectName("tab_tracker")
        self.btn_tracker_run = QtWidgets.QPushButton(self.tab_tracker)
        self.btn_tracker_run.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.btn_tracker_run.setObjectName("btn_tracker_run")
        self.btn_widget_tracker = QtWidgets.QPushButton(self.tab_tracker)
        self.btn_widget_tracker.setGeometry(QtCore.QRect(90, 20, 31, 23))
        self.btn_widget_tracker.setText("")
        self.btn_widget_tracker.setIcon(icon)
        self.btn_widget_tracker.setCheckable(True)
        self.btn_widget_tracker.setObjectName("btn_widget_tracker")
        self.dbl_tracker_xpos = QtWidgets.QDoubleSpinBox(self.tab_tracker)
        self.dbl_tracker_xpos.setGeometry(QtCore.QRect(180, 20, 60, 23))
        self.dbl_tracker_xpos.setObjectName("dbl_tracker_xpos")
        self.dbl_tracker_ypos = QtWidgets.QDoubleSpinBox(self.tab_tracker)
        self.dbl_tracker_ypos.setGeometry(QtCore.QRect(240, 20, 60, 23))
        self.dbl_tracker_ypos.setObjectName("dbl_tracker_ypos")
        self.dbl_tracker_zpos = QtWidgets.QDoubleSpinBox(self.tab_tracker)
        self.dbl_tracker_zpos.setGeometry(QtCore.QRect(300, 20, 60, 23))
        self.dbl_tracker_zpos.setObjectName("dbl_tracker_zpos")
        self.btn_tracker_home = QtWidgets.QPushButton(self.tab_tracker)
        self.btn_tracker_home.setGeometry(QtCore.QRect(360, 20, 51, 23))
        self.btn_tracker_home.setObjectName("btn_tracker_home")
        self.btn_tracker_drive = QtWidgets.QPushButton(self.tab_tracker)
        self.btn_tracker_drive.setGeometry(QtCore.QRect(130, 20, 51, 23))
        self.btn_tracker_drive.setObjectName("btn_tracker_drive")
        self.label_tracker_y = QtWidgets.QLabel(self.tab_tracker)
        self.label_tracker_y.setGeometry(QtCore.QRect(240, 2, 47, 13))
        self.label_tracker_y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tracker_y.setObjectName("label_tracker_y")
        self.label_tracker_x = QtWidgets.QLabel(self.tab_tracker)
        self.label_tracker_x.setGeometry(QtCore.QRect(180, 2, 47, 13))
        self.label_tracker_x.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tracker_x.setObjectName("label_tracker_x")
        self.label_tracker_z = QtWidgets.QLabel(self.tab_tracker)
        self.label_tracker_z.setGeometry(QtCore.QRect(300, 2, 47, 13))
        self.label_tracker_z.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tracker_z.setObjectName("label_tracker_z")
        self.glw_tracker = GraphicsLayoutWidget(self.tab_tracker)
        self.glw_tracker.setGeometry(QtCore.QRect(10, 80, 401, 701))
        self.glw_tracker.setObjectName("glw_tracker")
        self.chkbx_tracker_period = QtWidgets.QCheckBox(self.tab_tracker)
        self.chkbx_tracker_period.setGeometry(QtCore.QRect(10, 790, 70, 23))
        self.chkbx_tracker_period.setObjectName("chkbx_tracker_period")
        self.dbl_tracker_period = QtWidgets.QDoubleSpinBox(self.tab_tracker)
        self.dbl_tracker_period.setGeometry(QtCore.QRect(90, 790, 51, 23))
        self.dbl_tracker_period.setObjectName("dbl_tracker_period")
        self.btn_tracker_auto = QtWidgets.QPushButton(self.tab_tracker)
        self.btn_tracker_auto.setGeometry(QtCore.QRect(150, 790, 81, 23))
        self.btn_tracker_auto.setCheckable(True)
        self.btn_tracker_auto.setFlat(False)
        self.btn_tracker_auto.setObjectName("btn_tracker_auto")
        self.chkbx_nvlist_update = QtWidgets.QCheckBox(self.tab_tracker)
        self.chkbx_nvlist_update.setGeometry(QtCore.QRect(240, 790, 91, 23))
        self.chkbx_nvlist_update.setObjectName("chkbx_nvlist_update")
        self.btn_tracker_clear = QtWidgets.QPushButton(self.tab_tracker)
        self.btn_tracker_clear.setGeometry(QtCore.QRect(340, 790, 71, 23))
        self.btn_tracker_clear.setCheckable(False)
        self.btn_tracker_clear.setFlat(False)
        self.btn_tracker_clear.setObjectName("btn_tracker_clear")
        self.dbl_tracker_wait = QtWidgets.QDoubleSpinBox(self.tab_tracker)
        self.dbl_tracker_wait.setGeometry(QtCore.QRect(130, 50, 62, 22))
        self.dbl_tracker_wait.setObjectName("dbl_tracker_wait")
        self.label = QtWidgets.QLabel(self.tab_tracker)
        self.label.setGeometry(QtCore.QRect(40, 50, 91, 16))
        self.label.setObjectName("label")
        self.tab_toolbox.addTab(self.tab_tracker, "")
        self.tab_pulseblaster = QtWidgets.QWidget()
        self.tab_pulseblaster.setObjectName("tab_pulseblaster")
        self.btn_pb_cw = QtWidgets.QPushButton(self.tab_pulseblaster)
        self.btn_pb_cw.setGeometry(QtCore.QRect(20, 20, 81, 23))
        self.btn_pb_cw.setObjectName("btn_pb_cw")
        self.btn_pb_run = QtWidgets.QPushButton(self.tab_pulseblaster)
        self.btn_pb_run.setGeometry(QtCore.QRect(20, 50, 81, 23))
        self.btn_pb_run.setObjectName("btn_pb_run")
        self.btn_pb_stop = QtWidgets.QPushButton(self.tab_pulseblaster)
        self.btn_pb_stop.setGeometry(QtCore.QRect(20, 80, 81, 23))
        self.btn_pb_stop.setObjectName("btn_pb_stop")
        self.linein_trackinglaser = QtWidgets.QLineEdit(self.tab_pulseblaster)
        self.linein_trackinglaser.setGeometry(QtCore.QRect(110, 20, 81, 23))
        self.linein_trackinglaser.setMouseTracking(True)
        self.linein_trackinglaser.setObjectName("linein_trackinglaser")
        self.btn_pb_static = QtWidgets.QPushButton(self.tab_pulseblaster)
        self.btn_pb_static.setGeometry(QtCore.QRect(270, 20, 75, 23))
        self.btn_pb_static.setObjectName("btn_pb_static")
        self.chkbx_pb8 = QtWidgets.QCheckBox(self.tab_pulseblaster)
        self.chkbx_pb8.setGeometry(QtCore.QRect(270, 210, 141, 17))
        self.chkbx_pb8.setObjectName("chkbx_pb8")
        self.chkbx_pb4 = QtWidgets.QCheckBox(self.tab_pulseblaster)
        self.chkbx_pb4.setGeometry(QtCore.QRect(270, 130, 141, 17))
        self.chkbx_pb4.setObjectName("chkbx_pb4")
        self.chkbx_pb5 = QtWidgets.QCheckBox(self.tab_pulseblaster)
        self.chkbx_pb5.setGeometry(QtCore.QRect(270, 150, 141, 17))
        self.chkbx_pb5.setObjectName("chkbx_pb5")
        self.chkbx_pb6 = QtWidgets.QCheckBox(self.tab_pulseblaster)
        self.chkbx_pb6.setGeometry(QtCore.QRect(270, 170, 141, 17))
        self.chkbx_pb6.setObjectName("chkbx_pb6")
        self.chkbx_pb7 = QtWidgets.QCheckBox(self.tab_pulseblaster)
        self.chkbx_pb7.setGeometry(QtCore.QRect(270, 190, 141, 17))
        self.chkbx_pb7.setObjectName("chkbx_pb7")
        self.chkbx_pb3 = QtWidgets.QCheckBox(self.tab_pulseblaster)
        self.chkbx_pb3.setGeometry(QtCore.QRect(270, 110, 141, 17))
        self.chkbx_pb3.setObjectName("chkbx_pb3")
        self.chkbx_pb0 = QtWidgets.QCheckBox(self.tab_pulseblaster)
        self.chkbx_pb0.setGeometry(QtCore.QRect(270, 50, 141, 17))
        self.chkbx_pb0.setObjectName("chkbx_pb0")
        self.chkbx_pb2 = QtWidgets.QCheckBox(self.tab_pulseblaster)
        self.chkbx_pb2.setGeometry(QtCore.QRect(270, 90, 141, 17))
        self.chkbx_pb2.setObjectName("chkbx_pb2")
        self.chkbx_pb1 = QtWidgets.QCheckBox(self.tab_pulseblaster)
        self.chkbx_pb1.setGeometry(QtCore.QRect(270, 70, 141, 17))
        self.chkbx_pb1.setObjectName("chkbx_pb1")
        self.chkbx_pb9 = QtWidgets.QCheckBox(self.tab_pulseblaster)
        self.chkbx_pb9.setGeometry(QtCore.QRect(270, 230, 141, 17))
        self.chkbx_pb9.setObjectName("chkbx_pb9")
        self.chkbx_pb10 = QtWidgets.QCheckBox(self.tab_pulseblaster)
        self.chkbx_pb10.setGeometry(QtCore.QRect(270, 250, 141, 17))
        self.chkbx_pb10.setObjectName("chkbx_pb10")
        self.chkbx_pb11 = QtWidgets.QCheckBox(self.tab_pulseblaster)
        self.chkbx_pb11.setGeometry(QtCore.QRect(270, 270, 141, 17))
        self.chkbx_pb11.setObjectName("chkbx_pb11")
        self.btn_pb_update_dict = QtWidgets.QPushButton(self.tab_pulseblaster)
        self.btn_pb_update_dict.setGeometry(QtCore.QRect(270, 290, 81, 31))
        self.btn_pb_update_dict.setObjectName("btn_pb_update_dict")
        self.groupBox_pbcustom = QtWidgets.QGroupBox(self.tab_pulseblaster)
        self.groupBox_pbcustom.setGeometry(QtCore.QRect(10, 340, 401, 461))
        self.groupBox_pbcustom.setObjectName("groupBox_pbcustom")
        self.table_pbcustom = QtWidgets.QTableWidget(self.groupBox_pbcustom)
        self.table_pbcustom.setGeometry(QtCore.QRect(10, 20, 351, 401))
        self.table_pbcustom.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_pbcustom.setRowCount(0)
        self.table_pbcustom.setColumnCount(4)
        self.table_pbcustom.setObjectName("table_pbcustom")
        self.table_pbcustom.horizontalHeader().setDefaultSectionSize(50)
        self.table_pbcustom.verticalHeader().setDefaultSectionSize(20)
        self.table_pbcustom.verticalHeader().setMinimumSectionSize(20)
        self.btn_pbcustom_add = QtWidgets.QPushButton(self.groupBox_pbcustom)
        self.btn_pbcustom_add.setGeometry(QtCore.QRect(370, 20, 21, 23))
        self.btn_pbcustom_add.setObjectName("btn_pbcustom_add")
        self.btn_pbcustom_del = QtWidgets.QPushButton(self.groupBox_pbcustom)
        self.btn_pbcustom_del.setGeometry(QtCore.QRect(370, 50, 21, 23))
        self.btn_pbcustom_del.setObjectName("btn_pbcustom_del")
        self.btn_pbcustom_run = QtWidgets.QPushButton(self.groupBox_pbcustom)
        self.btn_pbcustom_run.setGeometry(QtCore.QRect(10, 430, 81, 23))
        self.btn_pbcustom_run.setObjectName("btn_pbcustom_run")
        self.btn_pbcustom_load = QtWidgets.QPushButton(self.groupBox_pbcustom)
        self.btn_pbcustom_load.setGeometry(QtCore.QRect(190, 430, 81, 23))
        self.btn_pbcustom_load.setObjectName("btn_pbcustom_load")
        self.btn_pbcustom_save = QtWidgets.QPushButton(self.groupBox_pbcustom)
        self.btn_pbcustom_save.setGeometry(QtCore.QRect(280, 430, 81, 23))
        self.btn_pbcustom_save.setObjectName("btn_pbcustom_save")
        self.btn_pb_update_pulse_list = QtWidgets.QPushButton(self.tab_pulseblaster)
        self.btn_pb_update_pulse_list.setGeometry(QtCore.QRect(20, 290, 131, 31))
        self.btn_pb_update_pulse_list.setObjectName("btn_pb_update_pulse_list")
        self.btn_pb_load_params = QtWidgets.QPushButton(self.tab_pulseblaster)
        self.btn_pb_load_params.setGeometry(QtCore.QRect(20, 180, 131, 31))
        self.btn_pb_load_params.setObjectName("btn_pb_load_params")
        self.tab_toolbox.addTab(self.tab_pulseblaster, "")
        self.tab_instruments = QtWidgets.QWidget()
        self.tab_instruments.setObjectName("tab_instruments")
        self.inst_label_mw1 = QtWidgets.QLabel(self.tab_instruments)
        self.inst_label_mw1.setGeometry(QtCore.QRect(20, 40, 141, 31))
        self.inst_label_mw1.setObjectName("inst_label_mw1")
        self.inst_chkbx_mw1_enable = QtWidgets.QCheckBox(self.tab_instruments)
        self.inst_chkbx_mw1_enable.setGeometry(QtCore.QRect(170, 40, 21, 31))
        self.inst_chkbx_mw1_enable.setText("")
        self.inst_chkbx_mw1_enable.setObjectName("inst_chkbx_mw1_enable")
        self.inst_btn_mw1_onoff = QtWidgets.QPushButton(self.tab_instruments)
        self.inst_btn_mw1_onoff.setGeometry(QtCore.QRect(190, 40, 41, 31))
        self.inst_btn_mw1_onoff.setCheckable(True)
        self.inst_btn_mw1_onoff.setFlat(False)
        self.inst_btn_mw1_onoff.setObjectName("inst_btn_mw1_onoff")
        self.inst_btn_mw1_iq = QtWidgets.QPushButton(self.tab_instruments)
        self.inst_btn_mw1_iq.setGeometry(QtCore.QRect(230, 40, 41, 31))
        self.inst_btn_mw1_iq.setCheckable(True)
        self.inst_btn_mw1_iq.setObjectName("inst_btn_mw1_iq")
        self.inst_btn_mw1_pulse = QtWidgets.QPushButton(self.tab_instruments)
        self.inst_btn_mw1_pulse.setGeometry(QtCore.QRect(370, 40, 41, 31))
        self.inst_btn_mw1_pulse.setCheckable(True)
        self.inst_btn_mw1_pulse.setObjectName("inst_btn_mw1_pulse")
        self.inst_label_mw2 = QtWidgets.QLabel(self.tab_instruments)
        self.inst_label_mw2.setGeometry(QtCore.QRect(20, 70, 141, 31))
        self.inst_label_mw2.setObjectName("inst_label_mw2")
        self.inst_chkbx_mw2_enable = QtWidgets.QCheckBox(self.tab_instruments)
        self.inst_chkbx_mw2_enable.setGeometry(QtCore.QRect(170, 70, 21, 31))
        self.inst_chkbx_mw2_enable.setText("")
        self.inst_chkbx_mw2_enable.setObjectName("inst_chkbx_mw2_enable")
        self.inst_btn_mw2_onoff = QtWidgets.QPushButton(self.tab_instruments)
        self.inst_btn_mw2_onoff.setGeometry(QtCore.QRect(190, 70, 41, 31))
        self.inst_btn_mw2_onoff.setCheckable(True)
        self.inst_btn_mw2_onoff.setFlat(False)
        self.inst_btn_mw2_onoff.setObjectName("inst_btn_mw2_onoff")
        self.inst_btn_mw2_iq = QtWidgets.QPushButton(self.tab_instruments)
        self.inst_btn_mw2_iq.setGeometry(QtCore.QRect(230, 70, 41, 31))
        self.inst_btn_mw2_iq.setCheckable(True)
        self.inst_btn_mw2_iq.setObjectName("inst_btn_mw2_iq")
        self.inst_btn_mw2_pulse = QtWidgets.QPushButton(self.tab_instruments)
        self.inst_btn_mw2_pulse.setGeometry(QtCore.QRect(370, 70, 41, 31))
        self.inst_btn_mw2_pulse.setCheckable(True)
        self.inst_btn_mw2_pulse.setObjectName("inst_btn_mw2_pulse")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_instruments)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 280, 401, 321))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.grid_inst_btn = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.grid_inst_btn.setContentsMargins(0, 0, 0, 0)
        self.grid_inst_btn.setObjectName("grid_inst_btn")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab_instruments)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 630, 401, 181))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.grid_inst_controls = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.grid_inst_controls.setContentsMargins(0, 0, 0, 0)
        self.grid_inst_controls.setObjectName("grid_inst_controls")
        self.label_inst_controls = QtWidgets.QLabel(self.tab_instruments)
        self.label_inst_controls.setGeometry(QtCore.QRect(10, 610, 81, 16))
        self.label_inst_controls.setObjectName("label_inst_controls")
        self.label_wavemeter_freq = QtWidgets.QLabel(self.tab_instruments)
        self.label_wavemeter_freq.setGeometry(QtCore.QRect(20, 250, 201, 16))
        self.label_wavemeter_freq.setObjectName("label_wavemeter_freq")
        self.tab_toolbox.addTab(self.tab_instruments, "")
        self.tab_autoZ = QtWidgets.QWidget()
        self.tab_autoZ.setObjectName("tab_autoZ")
        self.table_confocalZ = QtWidgets.QTableWidget(self.tab_autoZ)
        self.table_confocalZ.setGeometry(QtCore.QRect(10, 20, 321, 181))
        self.table_confocalZ.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_confocalZ.setObjectName("table_confocalZ")
        self.table_confocalZ.setColumnCount(0)
        self.table_confocalZ.setRowCount(0)
        self.btn_confocalZ_add = QtWidgets.QPushButton(self.tab_autoZ)
        self.btn_confocalZ_add.setGeometry(QtCore.QRect(340, 20, 41, 31))
        self.btn_confocalZ_add.setObjectName("btn_confocalZ_add")
        self.btn_confocalZ_del = QtWidgets.QPushButton(self.tab_autoZ)
        self.btn_confocalZ_del.setGeometry(QtCore.QRect(340, 60, 41, 31))
        self.btn_confocalZ_del.setObjectName("btn_confocalZ_del")
        self.btn_confocalZ_calc = QtWidgets.QPushButton(self.tab_autoZ)
        self.btn_confocalZ_calc.setGeometry(QtCore.QRect(340, 172, 41, 31))
        self.btn_confocalZ_calc.setObjectName("btn_confocalZ_calc")
        self.label_confocalZ_eq = QtWidgets.QLabel(self.tab_autoZ)
        self.label_confocalZ_eq.setGeometry(QtCore.QRect(10, 220, 301, 16))
        self.label_confocalZ_eq.setObjectName("label_confocalZ_eq")
        self.tab_toolbox.addTab(self.tab_autoZ, "")
        self.btn_debug = QtWidgets.QPushButton(self.centralwidget)
        self.btn_debug.setGeometry(QtCore.QRect(1710, 0, 31, 23))
        self.btn_debug.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/bug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_debug.setIcon(icon1)
        self.btn_debug.setCheckable(False)
        self.btn_debug.setObjectName("btn_debug")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1751, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionSin = QtWidgets.QAction(MainWindow)
        self.actionSin.setObjectName("actionSin")
        self.actionLorentzian = QtWidgets.QAction(MainWindow)
        self.actionLorentzian.setObjectName("actionLorentzian")
        self.actionGaussian = QtWidgets.QAction(MainWindow)
        self.actionGaussian.setObjectName("actionGaussian")
        self.actionExpDecay = QtWidgets.QAction(MainWindow)
        self.actionExpDecay.setObjectName("actionExpDecay")
        self.actionPowerDecay = QtWidgets.QAction(MainWindow)
        self.actionPowerDecay.setObjectName("actionPowerDecay")
        self.actionN15pol = QtWidgets.QAction(MainWindow)
        self.actionN15pol.setObjectName("actionN15pol")

        self.retranslateUi(MainWindow)
        self.tab_main.setCurrentIndex(0)
        self.tab_toolbox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_confocal_start.setText(_translate("MainWindow", "Start"))
        self.btn_confocal_stop.setText(_translate("MainWindow", "Stop"))
        self.label_confocal_start.setText(_translate("MainWindow", "start"))
        self.label_confocal_stop.setText(_translate("MainWindow", "stop"))
        self.label_confocal_numdivs.setText(_translate("MainWindow", "# step"))
        self.label_confocal_x.setText(_translate("MainWindow", "x"))
        self.label_confocal_y.setText(_translate("MainWindow", "y"))
        self.label_confocal_z.setText(_translate("MainWindow", "z"))
        self.label_confocal_acqtime.setText(_translate("MainWindow", "Acq. Time (s)"))
        self.btn_confocal_save.setText(_translate("MainWindow", "Save"))
        self.btn_confocal_autoZ.setText(_translate("MainWindow", "Auto Z"))
        self.btn_confocal_mode_xy.setText(_translate("MainWindow", "XY Scan"))
        self.btn_confocal_mode_xz.setText(_translate("MainWindow", "XZ Scan"))
        self.btn_confocal_mode_yz.setText(_translate("MainWindow", "YZ Scan"))
        self.chkbx_confocal_autolevel.setText(_translate("MainWindow", "auto level"))
        self.label_stage_x.setText(_translate("MainWindow", "stage_x"))
        self.label_stage_y.setText(_translate("MainWindow", "stage_y"))
        self.chkbx_confocal_esr.setText(_translate("MainWindow", "Check ESR Contrast"))
        self.btn_confocal_live.setText(_translate("MainWindow", "LIVE"))
        self.label_confocal_live_avg.setText(_translate("MainWindow", "# avg"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_confocal), _translate("MainWindow", "Confocal"))
        self.btn_exp_start.setText(_translate("MainWindow", "Run"))
        self.btn_exp_stop.setText(_translate("MainWindow", "Stop"))
        self.btn_swap_var.setText(_translate("MainWindow", ":"))
        self.chkbx_exp_logx.setText(_translate("MainWindow", "log"))
        self.chkbx_exp_autofit.setText(_translate("MainWindow", "Fit:"))
        self.label_exp_var_name.setText(_translate("MainWindow", "Sweep Variable"))
        self.label_exp_var_start.setText(_translate("MainWindow", "Start"))
        self.label_exp_var_stop.setText(_translate("MainWindow", "Stop"))
        self.label_exp_var_numdivs.setText(_translate("MainWindow", "# Steps"))
        self.label_exp_var_delay.setText(_translate("MainWindow", "Delay"))
        self.label_exp_var1.setText(_translate("MainWindow", "X"))
        self.label_exp_var2.setText(_translate("MainWindow", "Y"))
        self.chkbx_beep.setText(_translate("MainWindow", "beep when done"))
        self.btn_exp_save.setText(_translate("MainWindow", "Save"))
        self.btn_exp_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.chkbx_2dexp_meander.setText(_translate("MainWindow", "meander"))
        self.chkbx_PLE_fast.setText(_translate("MainWindow", "fast PLE sweep"))
        self.chkbx_newctr_2d.setText(_translate("MainWindow", "individual traces"))
        self.label_filename.setText(_translate("MainWindow", "label_filename"))
        self.label_nvlist.setText(_translate("MainWindow", "NV #"))
        self.label_exp_name.setText(_translate("MainWindow", "EXP:"))
        self.label_exp_pause.setText(_translate("MainWindow", "TextLabel"))
        self.btn_exp_pause.setText(_translate("MainWindow", "GO"))
        self.label_exp_params.setText(_translate("MainWindow", "label_exp_params"))
        self.btn_exp_fit.setText(_translate("MainWindow", "Fit"))
        self.btn_exp_fit.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_exp), _translate("MainWindow", "Pulsed Experiments"))
        self.chkbx_spectrometer_xbin.setText(_translate("MainWindow", "enabled"))
        self.chkbx_spectrometer_ybin.setText(_translate("MainWindow", "enabled"))
        self.btn_spectrometer_acquire.setText(_translate("MainWindow", "Acquire"))
        self.btn_spectrometer_stop.setText(_translate("MainWindow", "Stop"))
        self.label_spectrometer_centerwavelength.setText(_translate("MainWindow", "center wavelength (nm)"))
        self.label_spectrometer_exptime.setText(_translate("MainWindow", "exposure time (s)"))
        self.label_spectrometer_xbin.setText(_translate("MainWindow", "x-binning"))
        self.label_spectrometer_ybin.setText(_translate("MainWindow", "y-binning"))
        self.label_nvlist_spectrometer.setText(_translate("MainWindow", "NV #"))
        self.label_spectrometer_start.setText(_translate("MainWindow", "Start"))
        self.label_spectrometer_start_2.setText(_translate("MainWindow", "Stop"))
        self.btn_spectrometer_save.setText(_translate("MainWindow", "Save"))
        self.label_spectrometer_temp.setText(_translate("MainWindow", "label_spectrometer_temp"))
        self.btn_spectrometer_live.setText(_translate("MainWindow", "Live"))
        self.btn_spectrometer_connect.setText(_translate("MainWindow", "Connect"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_spectrometer), _translate("MainWindow", "Spectrometer"))
        self.label_sample_name.setText(_translate("MainWindow", "Sample:"))
        self.chkbx_autosave.setText(_translate("MainWindow", "Auto Save"))
        self.label_p532.setText(_translate("MainWindow", "label_p532"))
        self.groupBox_logdisp.setTitle(_translate("MainWindow", "Message Log"))
        self.groupBox_confocal.setTitle(_translate("MainWindow", "Confocal Image"))
        self.linein_map.setText(_translate("MainWindow", "linein_map"))
        self.btn_map_load.setText(_translate("MainWindow", "Load"))
        self.btn_map_copy.setText(_translate("MainWindow", "Copy"))
        self.btn_map_select.setText(_translate("MainWindow", "Select"))
        self.groupBox_expinfo.setTitle(_translate("MainWindow", "Experiments"))
        self.groupBox_modules.setTitle(_translate("MainWindow", "Modules"))
        self.btn_widget_liveapd.setText(_translate("MainWindow", "LIVE APD"))
        self.btn_widget_seqapd.setText(_translate("MainWindow", "SEQ APD"))
        self.btn_widget_satcurve.setText(_translate("MainWindow", "SAT CURVE"))
        self.btn_widget_histogram.setText(_translate("MainWindow", "HISTOGRAM"))
        self.btn_widget_picoharp.setText(_translate("MainWindow", "PICOHARP"))
        self.btn_widget_calculator.setText(_translate("MainWindow", "CALCULATOR"))
        self.btn_widget_batch.setText(_translate("MainWindow", "BATCH"))
        self.btn_widget_terminal.setText(_translate("MainWindow", "TERMINAL"))
        self.groupBox_plnorm.setTitle(_translate("MainWindow", "PL Normalization"))
        self.label_plnorm_bright.setText(_translate("MainWindow", "PL bright"))
        self.label_plnorm_dark.setText(_translate("MainWindow", "PL dark"))
        self.chkbx_plnorm.setText(_translate("MainWindow", "Norm. Data"))
        self.groupBox_fits.setTitle(_translate("MainWindow", "Fitting Parameters"))
        self.chkbx_row_timings.setText(_translate("MainWindow", "row timings"))
        self.chkbx_readoutcal.setText(_translate("MainWindow", "readout calibration"))
        self.chkbx_inv2.setText(_translate("MainWindow", "inv2 (**)"))
        self.chkbx_inv.setText(_translate("MainWindow", "phase inv (*)"))
        self.label_sweep_time_est.setText(_translate("MainWindow", "label_sweep_time_est"))
        self.groupBox.setTitle(_translate("MainWindow", "Shortcuts"))
        self.btn_tracker_run.setText(_translate("MainWindow", "Track"))
        self.btn_tracker_run.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.btn_tracker_home.setText(_translate("MainWindow", "Home"))
        self.btn_tracker_drive.setText(_translate("MainWindow", "drive"))
        self.label_tracker_y.setText(_translate("MainWindow", "y"))
        self.label_tracker_x.setText(_translate("MainWindow", "x"))
        self.label_tracker_z.setText(_translate("MainWindow", "z"))
        self.chkbx_tracker_period.setText(_translate("MainWindow", "time (min)"))
        self.btn_tracker_auto.setText(_translate("MainWindow", "Track on Idle"))
        self.chkbx_nvlist_update.setText(_translate("MainWindow", "Update NV List"))
        self.btn_tracker_clear.setText(_translate("MainWindow", "Clear Log"))
        self.label.setText(_translate("MainWindow", "Tracker Wait (s):"))
        self.tab_toolbox.setTabText(self.tab_toolbox.indexOf(self.tab_tracker), _translate("MainWindow", "Tracker"))
        self.btn_pb_cw.setText(_translate("MainWindow", "Main CW"))
        self.btn_pb_run.setText(_translate("MainWindow", "Pulse Program"))
        self.btn_pb_stop.setText(_translate("MainWindow", "Off"))
        self.linein_trackinglaser.setText(_translate("MainWindow", "green"))
        self.btn_pb_static.setText(_translate("MainWindow", "CW"))
        self.chkbx_pb8.setText(_translate("MainWindow", "PB8"))
        self.chkbx_pb4.setText(_translate("MainWindow", "PB4 (mw1)"))
        self.chkbx_pb5.setText(_translate("MainWindow", "PB5 (mw2)"))
        self.chkbx_pb6.setText(_translate("MainWindow", "PB6"))
        self.chkbx_pb7.setText(_translate("MainWindow", "PB7"))
        self.chkbx_pb3.setText(_translate("MainWindow", "PB3 (ctr1)"))
        self.chkbx_pb0.setText(_translate("MainWindow", "PB0 (blank green)"))
        self.chkbx_pb2.setText(_translate("MainWindow", "PB2 (ctr0)"))
        self.chkbx_pb1.setText(_translate("MainWindow", "PB1"))
        self.chkbx_pb9.setText(_translate("MainWindow", "PB9"))
        self.chkbx_pb10.setText(_translate("MainWindow", "PB10"))
        self.chkbx_pb11.setText(_translate("MainWindow", "PB11"))
        self.btn_pb_update_dict.setText(_translate("MainWindow", "Reload pb_dict"))
        self.groupBox_pbcustom.setTitle(_translate("MainWindow", "Custom Program"))
        self.btn_pbcustom_add.setText(_translate("MainWindow", "+"))
        self.btn_pbcustom_del.setText(_translate("MainWindow", "-"))
        self.btn_pbcustom_run.setText(_translate("MainWindow", "Start"))
        self.btn_pbcustom_load.setText(_translate("MainWindow", "Load"))
        self.btn_pbcustom_save.setText(_translate("MainWindow", "Save"))
        self.btn_pb_update_pulse_list.setText(_translate("MainWindow", "Reload Pulse Functions"))
        self.btn_pb_load_params.setText(_translate("MainWindow", "Pulse Params from .yaml"))
        self.tab_toolbox.setTabText(self.tab_toolbox.indexOf(self.tab_pulseblaster), _translate("MainWindow", "PulseBlaster"))
        self.inst_label_mw1.setText(_translate("MainWindow", "MW1"))
        self.inst_btn_mw1_onoff.setText(_translate("MainWindow", "On"))
        self.inst_btn_mw1_iq.setText(_translate("MainWindow", "IQ"))
        self.inst_btn_mw1_pulse.setText(_translate("MainWindow", "Pulse"))
        self.inst_label_mw2.setText(_translate("MainWindow", "MW2"))
        self.inst_btn_mw2_onoff.setText(_translate("MainWindow", "On"))
        self.inst_btn_mw2_iq.setText(_translate("MainWindow", "IQ"))
        self.inst_btn_mw2_pulse.setText(_translate("MainWindow", "Pulse"))
        self.label_inst_controls.setText(_translate("MainWindow", "Control Panels"))
        self.label_wavemeter_freq.setText(_translate("MainWindow", "label_wavemeter_freq"))
        self.tab_toolbox.setTabText(self.tab_toolbox.indexOf(self.tab_instruments), _translate("MainWindow", "Instruments"))
        self.btn_confocalZ_add.setText(_translate("MainWindow", "+"))
        self.btn_confocalZ_del.setText(_translate("MainWindow", "-"))
        self.btn_confocalZ_calc.setText(_translate("MainWindow", "Calc"))
        self.label_confocalZ_eq.setText(_translate("MainWindow", "label_confocalZ_eq"))
        self.tab_toolbox.setTabText(self.tab_toolbox.indexOf(self.tab_autoZ), _translate("MainWindow", "Z Correction"))
        self.actionSin.setText(_translate("MainWindow", "Sin"))
        self.actionLorentzian.setText(_translate("MainWindow", "Lorentzian"))
        self.actionGaussian.setText(_translate("MainWindow", "Gaussian"))
        self.actionExpDecay.setText(_translate("MainWindow", "Exp Decay"))
        self.actionPowerDecay.setText(_translate("MainWindow", "Power Decay"))
        self.actionN15pol.setText(_translate("MainWindow", "N15pol"))

from pyqtgraph import GraphicsLayoutWidget
import icon_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

