# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mat_browser.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 838)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineindir = QtWidgets.QLineEdit(self.centralwidget)
        self.lineindir.setGeometry(QtCore.QRect(100, 30, 911, 20))
        self.lineindir.setObjectName("lineindir")
        self.btnbrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnbrowse.setGeometry(QtCore.QRect(30, 30, 51, 21))
        self.btnbrowse.setObjectName("btnbrowse")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 1001, 731))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_afm = QtWidgets.QWidget()
        self.tab_afm.setObjectName("tab_afm")
        self.label_afm_img = QtWidgets.QLabel(self.tab_afm)
        self.label_afm_img.setGeometry(QtCore.QRect(310, 360, 671, 321))
        self.label_afm_img.setText("")
        self.label_afm_img.setObjectName("label_afm_img")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_afm)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(310, 10, 431, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_afm = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_afm.setContentsMargins(0, 0, 0, 0)
        self.grid_afm.setObjectName("grid_afm")
        self.table_afm = QtWidgets.QTableWidget(self.tab_afm)
        self.table_afm.setGeometry(QtCore.QRect(10, 10, 271, 671))
        self.table_afm.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_afm.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_afm.setObjectName("table_afm")
        self.table_afm.setColumnCount(0)
        self.table_afm.setRowCount(0)
        self.table_afm.verticalHeader().setVisible(False)
        self.label_afm_filename = QtWidgets.QLabel(self.tab_afm)
        self.label_afm_filename.setGeometry(QtCore.QRect(310, 330, 431, 16))
        self.label_afm_filename.setText("")
        self.label_afm_filename.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_afm_filename.setObjectName("label_afm_filename")
        self.tabWidget.addTab(self.tab_afm, "")
        self.tab_xps = QtWidgets.QWidget()
        self.tab_xps.setObjectName("tab_xps")
        self.table_xps = QtWidgets.QTableWidget(self.tab_xps)
        self.table_xps.setGeometry(QtCore.QRect(10, 10, 301, 691))
        self.table_xps.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_xps.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_xps.setObjectName("table_xps")
        self.table_xps.setColumnCount(0)
        self.table_xps.setRowCount(0)
        self.table_xps.verticalHeader().setVisible(False)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_xps)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(320, 260, 671, 411))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.grid_xps_fine = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.grid_xps_fine.setContentsMargins(0, 0, 0, 0)
        self.grid_xps_fine.setObjectName("grid_xps_fine")
        self.label_xps_filename = QtWidgets.QLabel(self.tab_xps)
        self.label_xps_filename.setGeometry(QtCore.QRect(320, 680, 671, 16))
        self.label_xps_filename.setText("")
        self.label_xps_filename.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_xps_filename.setObjectName("label_xps_filename")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_xps)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(320, 10, 671, 241))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.grid_xps_survey = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.grid_xps_survey.setContentsMargins(0, 0, 0, 0)
        self.grid_xps_survey.setObjectName("grid_xps_survey")
        self.tabWidget.addTab(self.tab_xps, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AFM & XPS Data Browser"))
        self.btnbrowse.setText(_translate("MainWindow", "browse"))
        self.table_afm.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_afm), _translate("MainWindow", "AFM"))
        self.table_xps.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_xps), _translate("MainWindow", "XPS"))

