# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UHV_heat3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1337, 712)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_operate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_operate.setGeometry(QtCore.QRect(20, 30, 101, 71))
        self.btn_operate.setCheckable(True)
        self.btn_operate.setObjectName("btn_operate")
        self.lcd_temp = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_temp.setGeometry(QtCore.QRect(150, 30, 161, 71))
        self.lcd_temp.setDigitCount(6)
        self.lcd_temp.setObjectName("lcd_temp")
        self.label_temp = QtWidgets.QLabel(self.centralwidget)
        self.label_temp.setGeometry(QtCore.QRect(170, 10, 141, 20))
        self.label_temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_temp.setObjectName("label_temp")
        self.dbl_temp_setpoint_system = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dbl_temp_setpoint_system.setGeometry(QtCore.QRect(150, 180, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dbl_temp_setpoint_system.setFont(font)
        self.dbl_temp_setpoint_system.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_temp_setpoint_system.setKeyboardTracking(False)
        self.dbl_temp_setpoint_system.setDecimals(1)
        self.dbl_temp_setpoint_system.setMaximum(1300.0)
        self.dbl_temp_setpoint_system.setObjectName("dbl_temp_setpoint_system")
        self.label_Ic = QtWidgets.QLabel(self.centralwidget)
        self.label_Ic.setGeometry(QtCore.QRect(220, 230, 61, 19))
        self.label_Ic.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Ic.setObjectName("label_Ic")
        self.label_Uc = QtWidgets.QLabel(self.centralwidget)
        self.label_Uc.setGeometry(QtCore.QRect(400, 230, 51, 19))
        self.label_Uc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Uc.setObjectName("label_Uc")
        self.groupBox_heat_mode = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_heat_mode.setGeometry(QtCore.QRect(20, 230, 121, 91))
        self.groupBox_heat_mode.setObjectName("groupBox_heat_mode")
        self.radio_res = QtWidgets.QRadioButton(self.groupBox_heat_mode)
        self.radio_res.setGeometry(QtCore.QRect(10, 30, 111, 23))
        self.radio_res.setObjectName("radio_res")
        self.radio_eb = QtWidgets.QRadioButton(self.groupBox_heat_mode)
        self.radio_eb.setGeometry(QtCore.QRect(10, 60, 111, 23))
        self.radio_eb.setObjectName("radio_eb")
        self.label_Ue = QtWidgets.QLabel(self.centralwidget)
        self.label_Ue.setGeometry(QtCore.QRect(400, 300, 51, 19))
        self.label_Ue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Ue.setObjectName("label_Ue")
        self.label_Ie = QtWidgets.QLabel(self.centralwidget)
        self.label_Ie.setGeometry(QtCore.QRect(220, 300, 61, 19))
        self.label_Ie.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Ie.setObjectName("label_Ie")
        self.groupBox_oper_mode = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_oper_mode.setGeometry(QtCore.QRect(20, 330, 121, 91))
        self.groupBox_oper_mode.setObjectName("groupBox_oper_mode")
        self.radio_auto = QtWidgets.QRadioButton(self.groupBox_oper_mode)
        self.radio_auto.setGeometry(QtCore.QRect(10, 60, 111, 23))
        self.radio_auto.setObjectName("radio_auto")
        self.radio_manual = QtWidgets.QRadioButton(self.groupBox_oper_mode)
        self.radio_manual.setGeometry(QtCore.QRect(10, 30, 111, 23))
        self.radio_manual.setObjectName("radio_manual")
        self.dbl_Ic_setpoint = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dbl_Ic_setpoint.setGeometry(QtCore.QRect(160, 410, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dbl_Ic_setpoint.setFont(font)
        self.dbl_Ic_setpoint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_Ic_setpoint.setKeyboardTracking(False)
        self.dbl_Ic_setpoint.setDecimals(2)
        self.dbl_Ic_setpoint.setMaximum(8.0)
        self.dbl_Ic_setpoint.setSingleStep(0.1)
        self.dbl_Ic_setpoint.setObjectName("dbl_Ic_setpoint")
        self.dbl_Ue_setpoint = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dbl_Ue_setpoint.setGeometry(QtCore.QRect(330, 410, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dbl_Ue_setpoint.setFont(font)
        self.dbl_Ue_setpoint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_Ue_setpoint.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dbl_Ue_setpoint.setKeyboardTracking(False)
        self.dbl_Ue_setpoint.setDecimals(1)
        self.dbl_Ue_setpoint.setMaximum(750.0)
        self.dbl_Ue_setpoint.setSingleStep(0.1)
        self.dbl_Ue_setpoint.setObjectName("dbl_Ue_setpoint")
        self.label_Ic_setpoint = QtWidgets.QLabel(self.centralwidget)
        self.label_Ic_setpoint.setGeometry(QtCore.QRect(160, 380, 121, 20))
        self.label_Ic_setpoint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Ic_setpoint.setObjectName("label_Ic_setpoint")
        self.label_Ue_setpoint = QtWidgets.QLabel(self.centralwidget)
        self.label_Ue_setpoint.setGeometry(QtCore.QRect(330, 380, 121, 20))
        self.label_Ue_setpoint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Ue_setpoint.setObjectName("label_Ue_setpoint")
        self.glw_log = GraphicsLayoutWidget(self.centralwidget)
        self.glw_log.setGeometry(QtCore.QRect(490, 20, 821, 501))
        self.glw_log.setObjectName("glw_log")
        self.btn_log_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_log_clear.setGeometry(QtCore.QRect(1190, 530, 101, 31))
        self.btn_log_clear.setCheckable(False)
        self.btn_log_clear.setObjectName("btn_log_clear")
        self.btn_log_export = QtWidgets.QPushButton(self.centralwidget)
        self.btn_log_export.setGeometry(QtCore.QRect(490, 530, 81, 31))
        self.btn_log_export.setCheckable(False)
        self.btn_log_export.setObjectName("btn_log_export")
        self.groupBox_Ie = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Ie.setGeometry(QtCore.QRect(150, 460, 141, 171))
        self.groupBox_Ie.setObjectName("groupBox_Ie")
        self.btn_Ic_ramp = QtWidgets.QPushButton(self.groupBox_Ie)
        self.btn_Ic_ramp.setGeometry(QtCore.QRect(80, 130, 51, 31))
        self.btn_Ic_ramp.setCheckable(True)
        self.btn_Ic_ramp.setObjectName("btn_Ic_ramp")
        self.btn_Ic_hold = QtWidgets.QPushButton(self.groupBox_Ie)
        self.btn_Ic_hold.setGeometry(QtCore.QRect(10, 130, 51, 31))
        self.btn_Ic_hold.setCheckable(True)
        self.btn_Ic_hold.setObjectName("btn_Ic_hold")
        self.dbl_Ic_ramp_setpoint = QtWidgets.QDoubleSpinBox(self.groupBox_Ie)
        self.dbl_Ic_ramp_setpoint.setGeometry(QtCore.QRect(10, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dbl_Ic_ramp_setpoint.setFont(font)
        self.dbl_Ic_ramp_setpoint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_Ic_ramp_setpoint.setKeyboardTracking(False)
        self.dbl_Ic_ramp_setpoint.setDecimals(2)
        self.dbl_Ic_ramp_setpoint.setMaximum(8.0)
        self.dbl_Ic_ramp_setpoint.setSingleStep(0.1)
        self.dbl_Ic_ramp_setpoint.setObjectName("dbl_Ic_ramp_setpoint")
        self.dbl_Ic_ramp_time = QtWidgets.QDoubleSpinBox(self.groupBox_Ie)
        self.dbl_Ic_ramp_time.setGeometry(QtCore.QRect(10, 80, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dbl_Ic_ramp_time.setFont(font)
        self.dbl_Ic_ramp_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_Ic_ramp_time.setKeyboardTracking(False)
        self.dbl_Ic_ramp_time.setDecimals(1)
        self.dbl_Ic_ramp_time.setMaximum(200.0)
        self.dbl_Ic_ramp_time.setObjectName("dbl_Ic_ramp_time")
        self.lcd_Ic = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_Ic.setGeometry(QtCore.QRect(160, 250, 121, 41))
        self.lcd_Ic.setDigitCount(6)
        self.lcd_Ic.setObjectName("lcd_Ic")
        self.lcd_Uc = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_Uc.setGeometry(QtCore.QRect(330, 250, 121, 41))
        self.lcd_Uc.setDigitCount(6)
        self.lcd_Uc.setObjectName("lcd_Uc")
        self.lcd_Ie = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_Ie.setGeometry(QtCore.QRect(160, 320, 121, 41))
        self.lcd_Ie.setDigitCount(6)
        self.lcd_Ie.setObjectName("lcd_Ie")
        self.lcd_Ue = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_Ue.setGeometry(QtCore.QRect(330, 320, 121, 41))
        self.lcd_Ue.setDigitCount(6)
        self.lcd_Ue.setObjectName("lcd_Ue")
        self.groupBox_Ue = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Ue.setGeometry(QtCore.QRect(320, 460, 141, 171))
        self.groupBox_Ue.setObjectName("groupBox_Ue")
        self.btn_Ue_ramp = QtWidgets.QPushButton(self.groupBox_Ue)
        self.btn_Ue_ramp.setGeometry(QtCore.QRect(80, 130, 51, 31))
        self.btn_Ue_ramp.setCheckable(True)
        self.btn_Ue_ramp.setObjectName("btn_Ue_ramp")
        self.btn_Ue_hold = QtWidgets.QPushButton(self.groupBox_Ue)
        self.btn_Ue_hold.setGeometry(QtCore.QRect(10, 130, 51, 31))
        self.btn_Ue_hold.setCheckable(True)
        self.btn_Ue_hold.setObjectName("btn_Ue_hold")
        self.dbl_Ue_ramp_setpoint = QtWidgets.QDoubleSpinBox(self.groupBox_Ue)
        self.dbl_Ue_ramp_setpoint.setGeometry(QtCore.QRect(10, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dbl_Ue_ramp_setpoint.setFont(font)
        self.dbl_Ue_ramp_setpoint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_Ue_ramp_setpoint.setKeyboardTracking(False)
        self.dbl_Ue_ramp_setpoint.setDecimals(1)
        self.dbl_Ue_ramp_setpoint.setMaximum(750.0)
        self.dbl_Ue_ramp_setpoint.setSingleStep(1.0)
        self.dbl_Ue_ramp_setpoint.setObjectName("dbl_Ue_ramp_setpoint")
        self.dbl_Ue_ramp_time = QtWidgets.QDoubleSpinBox(self.groupBox_Ue)
        self.dbl_Ue_ramp_time.setGeometry(QtCore.QRect(10, 80, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dbl_Ue_ramp_time.setFont(font)
        self.dbl_Ue_ramp_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_Ue_ramp_time.setKeyboardTracking(False)
        self.dbl_Ue_ramp_time.setDecimals(1)
        self.dbl_Ue_ramp_time.setMaximum(200.0)
        self.dbl_Ue_ramp_time.setObjectName("dbl_Ue_ramp_time")
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(580, 540, 381, 19))
        self.label_time.setObjectName("label_time")
        self.label_temp_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_temp_2.setGeometry(QtCore.QRect(340, 10, 141, 20))
        self.label_temp_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_temp_2.setObjectName("label_temp_2")
        self.lcd_temp_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_temp_2.setGeometry(QtCore.QRect(320, 30, 161, 71))
        self.lcd_temp_2.setDigitCount(6)
        self.lcd_temp_2.setObjectName("lcd_temp_2")
        self.label_time_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_time_2.setGeometry(QtCore.QRect(580, 560, 381, 19))
        self.label_time_2.setObjectName("label_time_2")
        self.label_Ic_setpoint_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Ic_setpoint_2.setGeometry(QtCore.QRect(20, 500, 121, 20))
        self.label_Ic_setpoint_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Ic_setpoint_2.setObjectName("label_Ic_setpoint_2")
        self.label_Ic_setpoint_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Ic_setpoint_3.setGeometry(QtCore.QRect(10, 550, 131, 20))
        self.label_Ic_setpoint_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Ic_setpoint_3.setObjectName("label_Ic_setpoint_3")
        self.dbl_temp_setpoint_sample = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dbl_temp_setpoint_sample.setGeometry(QtCore.QRect(320, 180, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dbl_temp_setpoint_sample.setFont(font)
        self.dbl_temp_setpoint_sample.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_temp_setpoint_sample.setKeyboardTracking(False)
        self.dbl_temp_setpoint_sample.setDecimals(1)
        self.dbl_temp_setpoint_sample.setMaximum(1300.0)
        self.dbl_temp_setpoint_sample.setObjectName("dbl_temp_setpoint_sample")
        self.groupBox_temp_mode = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_temp_mode.setGeometry(QtCore.QRect(20, 120, 121, 91))
        self.groupBox_temp_mode.setObjectName("groupBox_temp_mode")
        self.radio_tsystem = QtWidgets.QRadioButton(self.groupBox_temp_mode)
        self.radio_tsystem.setGeometry(QtCore.QRect(10, 30, 111, 23))
        self.radio_tsystem.setObjectName("radio_tsystem")
        self.radio_tsample = QtWidgets.QRadioButton(self.groupBox_temp_mode)
        self.radio_tsample.setGeometry(QtCore.QRect(10, 60, 111, 23))
        self.radio_tsample.setObjectName("radio_tsample")
        self.label_Ic_setpoint_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_Ic_setpoint_4.setGeometry(QtCore.QRect(150, 110, 161, 20))
        self.label_Ic_setpoint_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Ic_setpoint_4.setObjectName("label_Ic_setpoint_4")
        self.dbl_temp_ramp = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dbl_temp_ramp.setGeometry(QtCore.QRect(390, 130, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dbl_temp_ramp.setFont(font)
        self.dbl_temp_ramp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_temp_ramp.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dbl_temp_ramp.setKeyboardTracking(False)
        self.dbl_temp_ramp.setDecimals(1)
        self.dbl_temp_ramp.setMaximum(60.0)
        self.dbl_temp_ramp.setSingleStep(1.0)
        self.dbl_temp_ramp.setObjectName("dbl_temp_ramp")
        self.label_Ic_setpoint_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_Ic_setpoint_5.setGeometry(QtCore.QRect(320, 110, 161, 20))
        self.label_Ic_setpoint_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Ic_setpoint_5.setObjectName("label_Ic_setpoint_5")
        self.lcd_temp_pid = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_temp_pid.setGeometry(QtCore.QRect(180, 130, 131, 41))
        self.lcd_temp_pid.setDigitCount(6)
        self.lcd_temp_pid.setObjectName("lcd_temp_pid")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1337, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HEAT3-PS"))
        self.btn_operate.setText(_translate("MainWindow", "Operate"))
        self.label_temp.setText(_translate("MainWindow", "System Temp (C)"))
        self.label_Ic.setText(_translate("MainWindow", "Ic (A)"))
        self.label_Uc.setText(_translate("MainWindow", "Uc (V)"))
        self.groupBox_heat_mode.setTitle(_translate("MainWindow", "Heating Mode"))
        self.radio_res.setText(_translate("MainWindow", "Resistive"))
        self.radio_eb.setText(_translate("MainWindow", "E-beam"))
        self.label_Ue.setText(_translate("MainWindow", "Ue (V)"))
        self.label_Ie.setText(_translate("MainWindow", "Ie (mA)"))
        self.groupBox_oper_mode.setTitle(_translate("MainWindow", "Operation"))
        self.radio_auto.setText(_translate("MainWindow", "Auto"))
        self.radio_manual.setText(_translate("MainWindow", "Manual"))
        self.label_Ic_setpoint.setText(_translate("MainWindow", "Ic setpoint (A)"))
        self.label_Ue_setpoint.setText(_translate("MainWindow", "Ue setpoint (V)"))
        self.btn_log_clear.setText(_translate("MainWindow", "Clear"))
        self.btn_log_export.setText(_translate("MainWindow", "Export"))
        self.groupBox_Ie.setTitle(_translate("MainWindow", "Ramp"))
        self.btn_Ic_ramp.setText(_translate("MainWindow", "ramp"))
        self.btn_Ic_hold.setText(_translate("MainWindow", "hold"))
        self.groupBox_Ue.setTitle(_translate("MainWindow", "Ramp"))
        self.btn_Ue_ramp.setText(_translate("MainWindow", "ramp"))
        self.btn_Ue_hold.setText(_translate("MainWindow", "hold"))
        self.label_time.setText(_translate("MainWindow", "time"))
        self.label_temp_2.setText(_translate("MainWindow", "Sample Temp (C)"))
        self.label_time_2.setText(_translate("MainWindow", "time"))
        self.label_Ic_setpoint_2.setText(_translate("MainWindow", "Ramp Setpoint"))
        self.label_Ic_setpoint_3.setText(_translate("MainWindow", "Ramp time (min)"))
        self.groupBox_temp_mode.setTitle(_translate("MainWindow", "Setpoint (C)"))
        self.radio_tsystem.setText(_translate("MainWindow", "System"))
        self.radio_tsample.setText(_translate("MainWindow", "Sample"))
        self.label_Ic_setpoint_4.setText(_translate("MainWindow", "Act. Setpoint "))
        self.label_Ic_setpoint_5.setText(_translate("MainWindow", "Ramp (C/min)"))

from pyqtgraph import GraphicsLayoutWidget
