# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UHV_System.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(504, 289)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.disp_IG2_pressure = QtWidgets.QLabel(self.centralwidget)
        self.disp_IG2_pressure.setGeometry(QtCore.QRect(120, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.disp_IG2_pressure.setFont(font)
        self.disp_IG2_pressure.setTextFormat(QtCore.Qt.AutoText)
        self.disp_IG2_pressure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.disp_IG2_pressure.setObjectName("disp_IG2_pressure")
        self.disp_IP1_pressure = QtWidgets.QLabel(self.centralwidget)
        self.disp_IP1_pressure.setGeometry(QtCore.QRect(120, 19, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.disp_IP1_pressure.setFont(font)
        self.disp_IP1_pressure.setTextFormat(QtCore.Qt.AutoText)
        self.disp_IP1_pressure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.disp_IP1_pressure.setObjectName("disp_IP1_pressure")
        self.disp_LL_pressure = QtWidgets.QLabel(self.centralwidget)
        self.disp_LL_pressure.setGeometry(QtCore.QRect(120, 240, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.disp_LL_pressure.setFont(font)
        self.disp_LL_pressure.setTextFormat(QtCore.Qt.AutoText)
        self.disp_LL_pressure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.disp_LL_pressure.setObjectName("disp_LL_pressure")
        self.disp_IP2_pressure = QtWidgets.QLabel(self.centralwidget)
        self.disp_IP2_pressure.setGeometry(QtCore.QRect(120, 60, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.disp_IP2_pressure.setFont(font)
        self.disp_IP2_pressure.setTextFormat(QtCore.Qt.AutoText)
        self.disp_IP2_pressure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.disp_IP2_pressure.setObjectName("disp_IP2_pressure")
        self.disp_IP2_voltage = QtWidgets.QLabel(self.centralwidget)
        self.disp_IP2_voltage.setGeometry(QtCore.QRect(400, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.disp_IP2_voltage.setFont(font)
        self.disp_IP2_voltage.setTextFormat(QtCore.Qt.AutoText)
        self.disp_IP2_voltage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.disp_IP2_voltage.setObjectName("disp_IP2_voltage")
        self.disp_IP1_voltage = QtWidgets.QLabel(self.centralwidget)
        self.disp_IP1_voltage.setGeometry(QtCore.QRect(400, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.disp_IP1_voltage.setFont(font)
        self.disp_IP1_voltage.setTextFormat(QtCore.Qt.AutoText)
        self.disp_IP1_voltage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.disp_IP1_voltage.setObjectName("disp_IP1_voltage")
        self.disp_IP2_current = QtWidgets.QLabel(self.centralwidget)
        self.disp_IP2_current.setGeometry(QtCore.QRect(310, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.disp_IP2_current.setFont(font)
        self.disp_IP2_current.setTextFormat(QtCore.Qt.AutoText)
        self.disp_IP2_current.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.disp_IP2_current.setObjectName("disp_IP2_current")
        self.label_IP1 = QtWidgets.QLabel(self.centralwidget)
        self.label_IP1.setGeometry(QtCore.QRect(20, 30, 101, 20))
        self.label_IP1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_IP1.setObjectName("label_IP1")
        self.disp_IP1_current = QtWidgets.QLabel(self.centralwidget)
        self.disp_IP1_current.setGeometry(QtCore.QRect(310, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.disp_IP1_current.setFont(font)
        self.disp_IP1_current.setTextFormat(QtCore.Qt.AutoText)
        self.disp_IP1_current.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.disp_IP1_current.setObjectName("disp_IP1_current")
        self.label_Pfeiffer = QtWidgets.QLabel(self.centralwidget)
        self.label_Pfeiffer.setGeometry(QtCore.QRect(20, 250, 101, 20))
        self.label_Pfeiffer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Pfeiffer.setObjectName("label_Pfeiffer")
        self.disp_IG1_pressure = QtWidgets.QLabel(self.centralwidget)
        self.disp_IG1_pressure.setGeometry(QtCore.QRect(120, 120, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.disp_IG1_pressure.setFont(font)
        self.disp_IG1_pressure.setTextFormat(QtCore.Qt.AutoText)
        self.disp_IG1_pressure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.disp_IG1_pressure.setObjectName("disp_IG1_pressure")
        self.label_IG1 = QtWidgets.QLabel(self.centralwidget)
        self.label_IG1.setGeometry(QtCore.QRect(20, 130, 101, 20))
        self.label_IG1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_IG1.setObjectName("label_IG1")
        self.label_IG2 = QtWidgets.QLabel(self.centralwidget)
        self.label_IG2.setGeometry(QtCore.QRect(20, 170, 101, 20))
        self.label_IG2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_IG2.setObjectName("label_IG2")
        self.label_IP2 = QtWidgets.QLabel(self.centralwidget)
        self.label_IP2.setGeometry(QtCore.QRect(20, 70, 101, 20))
        self.label_IP2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_IP2.setObjectName("label_IP2")
        self.chkbox_AlwaysOnTop = QtWidgets.QCheckBox(self.centralwidget)
        self.chkbox_AlwaysOnTop.setGeometry(QtCore.QRect(330, 250, 141, 23))
        self.chkbox_AlwaysOnTop.setObjectName("chkbox_AlwaysOnTop")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UHV System Control"))
        self.disp_IG2_pressure.setText(_translate("MainWindow", "IG2_pressure"))
        self.disp_IP1_pressure.setText(_translate("MainWindow", "IP1_pressure"))
        self.disp_LL_pressure.setText(_translate("MainWindow", "LL_pressure"))
        self.disp_IP2_pressure.setText(_translate("MainWindow", "IP2_pressure"))
        self.disp_IP2_voltage.setText(_translate("MainWindow", "IP2_Voltage"))
        self.disp_IP1_voltage.setText(_translate("MainWindow", "IP1_voltage"))
        self.disp_IP2_current.setText(_translate("MainWindow", "IP2_current"))
        self.label_IP1.setText(_translate("MainWindow", "Ion Pump 1"))
        self.disp_IP1_current.setText(_translate("MainWindow", "IP1_current"))
        self.label_Pfeiffer.setText(_translate("MainWindow", "Load Lock"))
        self.disp_IG1_pressure.setText(_translate("MainWindow", "IG1_pressure"))
        self.label_IG1.setText(_translate("MainWindow", "Ion Gauge 1"))
        self.label_IG2.setText(_translate("MainWindow", "Ion Gauge 2"))
        self.label_IP2.setText(_translate("MainWindow", "Ion Pump 2"))
        self.chkbox_AlwaysOnTop.setText(_translate("MainWindow", "Always on Top"))

