# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UHV_xr40b.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 406)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dbl_Uhv_setpoint = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dbl_Uhv_setpoint.setGeometry(QtCore.QRect(130, 120, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dbl_Uhv_setpoint.setFont(font)
        self.dbl_Uhv_setpoint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_Uhv_setpoint.setKeyboardTracking(False)
        self.dbl_Uhv_setpoint.setDecimals(1)
        self.dbl_Uhv_setpoint.setMinimum(0.5)
        self.dbl_Uhv_setpoint.setMaximum(20.0)
        self.dbl_Uhv_setpoint.setSingleStep(0.1)
        self.dbl_Uhv_setpoint.setObjectName("dbl_Uhv_setpoint")
        self.label_setpoint = QtWidgets.QLabel(self.centralwidget)
        self.label_setpoint.setGeometry(QtCore.QRect(50, 130, 71, 19))
        self.label_setpoint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_setpoint.setObjectName("label_setpoint")
        self.lcd_Uhv = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_Uhv.setGeometry(QtCore.QRect(130, 40, 161, 71))
        self.lcd_Uhv.setDigitCount(6)
        self.lcd_Uhv.setObjectName("lcd_Uhv")
        self.label_Uhv = QtWidgets.QLabel(self.centralwidget)
        self.label_Uhv.setGeometry(QtCore.QRect(160, 10, 131, 20))
        self.label_Uhv.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Uhv.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Uhv.setObjectName("label_Uhv")
        self.lcd_Ie = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_Ie.setGeometry(QtCore.QRect(310, 40, 161, 71))
        self.lcd_Ie.setDigitCount(6)
        self.lcd_Ie.setObjectName("lcd_Ie")
        self.label_Ie = QtWidgets.QLabel(self.centralwidget)
        self.label_Ie.setGeometry(QtCore.QRect(300, 10, 171, 20))
        self.label_Ie.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Ie.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Ie.setObjectName("label_Ie")
        self.dbl_Ie_setpoint = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dbl_Ie_setpoint.setGeometry(QtCore.QRect(310, 120, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dbl_Ie_setpoint.setFont(font)
        self.dbl_Ie_setpoint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_Ie_setpoint.setKeyboardTracking(False)
        self.dbl_Ie_setpoint.setDecimals(1)
        self.dbl_Ie_setpoint.setMaximum(40.0)
        self.dbl_Ie_setpoint.setSingleStep(0.1)
        self.dbl_Ie_setpoint.setObjectName("dbl_Ie_setpoint")
        self.btn_operate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_operate.setGeometry(QtCore.QRect(10, 40, 101, 71))
        self.btn_operate.setCheckable(True)
        self.btn_operate.setObjectName("btn_operate")
        self.groupBox_Uhv = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Uhv.setGeometry(QtCore.QRect(130, 170, 161, 171))
        self.groupBox_Uhv.setObjectName("groupBox_Uhv")
        self.btn_Uhv_ramp = QtWidgets.QPushButton(self.groupBox_Uhv)
        self.btn_Uhv_ramp.setGeometry(QtCore.QRect(90, 130, 61, 31))
        self.btn_Uhv_ramp.setCheckable(True)
        self.btn_Uhv_ramp.setObjectName("btn_Uhv_ramp")
        self.btn_Uhv_hold = QtWidgets.QPushButton(self.groupBox_Uhv)
        self.btn_Uhv_hold.setGeometry(QtCore.QRect(10, 130, 61, 31))
        self.btn_Uhv_hold.setCheckable(True)
        self.btn_Uhv_hold.setObjectName("btn_Uhv_hold")
        self.dbl_Uhv_ramp_setpoint = QtWidgets.QDoubleSpinBox(self.groupBox_Uhv)
        self.dbl_Uhv_ramp_setpoint.setGeometry(QtCore.QRect(10, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dbl_Uhv_ramp_setpoint.setFont(font)
        self.dbl_Uhv_ramp_setpoint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_Uhv_ramp_setpoint.setKeyboardTracking(False)
        self.dbl_Uhv_ramp_setpoint.setDecimals(1)
        self.dbl_Uhv_ramp_setpoint.setMaximum(20.0)
        self.dbl_Uhv_ramp_setpoint.setSingleStep(0.1)
        self.dbl_Uhv_ramp_setpoint.setObjectName("dbl_Uhv_ramp_setpoint")
        self.dbl_Uhv_ramp_time = QtWidgets.QDoubleSpinBox(self.groupBox_Uhv)
        self.dbl_Uhv_ramp_time.setGeometry(QtCore.QRect(10, 80, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dbl_Uhv_ramp_time.setFont(font)
        self.dbl_Uhv_ramp_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_Uhv_ramp_time.setKeyboardTracking(False)
        self.dbl_Uhv_ramp_time.setDecimals(1)
        self.dbl_Uhv_ramp_time.setMaximum(200.0)
        self.dbl_Uhv_ramp_time.setObjectName("dbl_Uhv_ramp_time")
        self.label_setpoint_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_setpoint_3.setGeometry(QtCore.QRect(30, 260, 91, 20))
        self.label_setpoint_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_setpoint_3.setObjectName("label_setpoint_3")
        self.label_setpoint_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_setpoint_2.setGeometry(QtCore.QRect(60, 210, 61, 20))
        self.label_setpoint_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_setpoint_2.setObjectName("label_setpoint_2")
        self.groupBox_Ie = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Ie.setGeometry(QtCore.QRect(310, 170, 161, 171))
        self.groupBox_Ie.setObjectName("groupBox_Ie")
        self.btn_Ie_ramp = QtWidgets.QPushButton(self.groupBox_Ie)
        self.btn_Ie_ramp.setGeometry(QtCore.QRect(90, 130, 61, 31))
        self.btn_Ie_ramp.setCheckable(True)
        self.btn_Ie_ramp.setObjectName("btn_Ie_ramp")
        self.btn_Ie_hold = QtWidgets.QPushButton(self.groupBox_Ie)
        self.btn_Ie_hold.setGeometry(QtCore.QRect(10, 130, 61, 31))
        self.btn_Ie_hold.setCheckable(True)
        self.btn_Ie_hold.setObjectName("btn_Ie_hold")
        self.dbl_Ie_ramp_setpoint = QtWidgets.QDoubleSpinBox(self.groupBox_Ie)
        self.dbl_Ie_ramp_setpoint.setGeometry(QtCore.QRect(10, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dbl_Ie_ramp_setpoint.setFont(font)
        self.dbl_Ie_ramp_setpoint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_Ie_ramp_setpoint.setKeyboardTracking(False)
        self.dbl_Ie_ramp_setpoint.setDecimals(1)
        self.dbl_Ie_ramp_setpoint.setMaximum(40.0)
        self.dbl_Ie_ramp_setpoint.setSingleStep(0.1)
        self.dbl_Ie_ramp_setpoint.setObjectName("dbl_Ie_ramp_setpoint")
        self.dbl_Ie_ramp_time = QtWidgets.QDoubleSpinBox(self.groupBox_Ie)
        self.dbl_Ie_ramp_time.setGeometry(QtCore.QRect(10, 80, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dbl_Ie_ramp_time.setFont(font)
        self.dbl_Ie_ramp_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_Ie_ramp_time.setKeyboardTracking(False)
        self.dbl_Ie_ramp_time.setDecimals(1)
        self.dbl_Ie_ramp_time.setMaximum(200.0)
        self.dbl_Ie_ramp_time.setObjectName("dbl_Ie_ramp_time")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "XR40B-EC"))
        self.label_setpoint.setText(_translate("MainWindow", "Setpoint"))
        self.label_Uhv.setText(_translate("MainWindow", "High Voltage (kV)"))
        self.label_Ie.setText(_translate("MainWindow", "Emission Current (mA)"))
        self.btn_operate.setText(_translate("MainWindow", "Operate"))
        self.groupBox_Uhv.setTitle(_translate("MainWindow", "Ramp"))
        self.btn_Uhv_ramp.setText(_translate("MainWindow", "ramp"))
        self.btn_Uhv_hold.setText(_translate("MainWindow", "hold"))
        self.label_setpoint_3.setText(_translate("MainWindow", "time (min)"))
        self.label_setpoint_2.setText(_translate("MainWindow", "Setpoint"))
        self.groupBox_Ie.setTitle(_translate("MainWindow", "Ramp"))
        self.btn_Ie_ramp.setText(_translate("MainWindow", "ramp"))
        self.btn_Ie_hold.setText(_translate("MainWindow", "hold"))

