# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_picoharp.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(560, 450)
        self.glw_picoharp = GraphicsLayoutWidget(Form)
        self.glw_picoharp.setGeometry(QtCore.QRect(10, 10, 541, 221))
        self.glw_picoharp.setObjectName("glw_picoharp")
        self.btn_picoharp_save = QtWidgets.QPushButton(Form)
        self.btn_picoharp_save.setGeometry(QtCore.QRect(510, 240, 41, 21))
        self.btn_picoharp_save.setObjectName("btn_picoharp_save")
        self.groupBox_ch0 = QtWidgets.QGroupBox(Form)
        self.groupBox_ch0.setGeometry(QtCore.QRect(20, 260, 141, 151))
        self.groupBox_ch0.setObjectName("groupBox_ch0")
        self.int_picoharp_ZeroCr0 = QtWidgets.QSpinBox(self.groupBox_ch0)
        self.int_picoharp_ZeroCr0.setGeometry(QtCore.QRect(10, 40, 51, 22))
        self.int_picoharp_ZeroCr0.setKeyboardTracking(False)
        self.int_picoharp_ZeroCr0.setMaximum(20)
        self.int_picoharp_ZeroCr0.setProperty("value", 10)
        self.int_picoharp_ZeroCr0.setObjectName("int_picoharp_ZeroCr0")
        self.int_picoharp_Discr0 = QtWidgets.QSpinBox(self.groupBox_ch0)
        self.int_picoharp_Discr0.setGeometry(QtCore.QRect(10, 90, 51, 22))
        self.int_picoharp_Discr0.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.int_picoharp_Discr0.setKeyboardTracking(False)
        self.int_picoharp_Discr0.setMaximum(800)
        self.int_picoharp_Discr0.setSingleStep(25)
        self.int_picoharp_Discr0.setProperty("value", 50)
        self.int_picoharp_Discr0.setObjectName("int_picoharp_Discr0")
        self.label_picoharp_ZeroCr0 = QtWidgets.QLabel(self.groupBox_ch0)
        self.label_picoharp_ZeroCr0.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_picoharp_ZeroCr0.setObjectName("label_picoharp_ZeroCr0")
        self.label_picoharp_Discr0 = QtWidgets.QLabel(self.groupBox_ch0)
        self.label_picoharp_Discr0.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_picoharp_Discr0.setObjectName("label_picoharp_Discr0")
        self.label_picoharp_offset0 = QtWidgets.QLabel(self.groupBox_ch0)
        self.label_picoharp_offset0.setGeometry(QtCore.QRect(80, 70, 61, 16))
        self.label_picoharp_offset0.setObjectName("label_picoharp_offset0")
        self.int_picoharp_offset0 = QtWidgets.QSpinBox(self.groupBox_ch0)
        self.int_picoharp_offset0.setGeometry(QtCore.QRect(80, 90, 51, 22))
        self.int_picoharp_offset0.setKeyboardTracking(False)
        self.int_picoharp_offset0.setMinimum(-999)
        self.int_picoharp_offset0.setMaximum(999)
        self.int_picoharp_offset0.setObjectName("int_picoharp_offset0")
        self.label_picoharp_rate0 = QtWidgets.QLabel(self.groupBox_ch0)
        self.label_picoharp_rate0.setGeometry(QtCore.QRect(10, 120, 61, 16))
        self.label_picoharp_rate0.setObjectName("label_picoharp_rate0")
        self.btn_picoharp_update_settings = QtWidgets.QPushButton(self.groupBox_ch0)
        self.btn_picoharp_update_settings.setGeometry(QtCore.QRect(80, 120, 51, 21))
        self.btn_picoharp_update_settings.setObjectName("btn_picoharp_update_settings")
        self.groupBox_ch1 = QtWidgets.QGroupBox(Form)
        self.groupBox_ch1.setGeometry(QtCore.QRect(170, 260, 81, 151))
        self.groupBox_ch1.setObjectName("groupBox_ch1")
        self.int_picoharp_ZeroCr1 = QtWidgets.QSpinBox(self.groupBox_ch1)
        self.int_picoharp_ZeroCr1.setGeometry(QtCore.QRect(10, 40, 51, 22))
        self.int_picoharp_ZeroCr1.setKeyboardTracking(False)
        self.int_picoharp_ZeroCr1.setMaximum(20)
        self.int_picoharp_ZeroCr1.setProperty("value", 10)
        self.int_picoharp_ZeroCr1.setObjectName("int_picoharp_ZeroCr1")
        self.int_picoharp_Discr1 = QtWidgets.QSpinBox(self.groupBox_ch1)
        self.int_picoharp_Discr1.setGeometry(QtCore.QRect(10, 90, 51, 22))
        self.int_picoharp_Discr1.setKeyboardTracking(False)
        self.int_picoharp_Discr1.setMaximum(800)
        self.int_picoharp_Discr1.setSingleStep(25)
        self.int_picoharp_Discr1.setProperty("value", 50)
        self.int_picoharp_Discr1.setObjectName("int_picoharp_Discr1")
        self.label_picoharp_ZeroCr1 = QtWidgets.QLabel(self.groupBox_ch1)
        self.label_picoharp_ZeroCr1.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_picoharp_ZeroCr1.setObjectName("label_picoharp_ZeroCr1")
        self.label_picoharp_Discr1 = QtWidgets.QLabel(self.groupBox_ch1)
        self.label_picoharp_Discr1.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_picoharp_Discr1.setObjectName("label_picoharp_Discr1")
        self.label_picoharp_rate1 = QtWidgets.QLabel(self.groupBox_ch1)
        self.label_picoharp_rate1.setGeometry(QtCore.QRect(10, 120, 61, 16))
        self.label_picoharp_rate1.setObjectName("label_picoharp_rate1")
        self.groupBox_acq = QtWidgets.QGroupBox(Form)
        self.groupBox_acq.setGeometry(QtCore.QRect(260, 260, 151, 181))
        self.groupBox_acq.setObjectName("groupBox_acq")
        self.int_picoharp_acqtime = QtWidgets.QSpinBox(self.groupBox_acq)
        self.int_picoharp_acqtime.setGeometry(QtCore.QRect(10, 90, 51, 22))
        self.int_picoharp_acqtime.setMaximum(100000)
        self.int_picoharp_acqtime.setSingleStep(10)
        self.int_picoharp_acqtime.setObjectName("int_picoharp_acqtime")
        self.label_picoharp_res = QtWidgets.QLabel(self.groupBox_acq)
        self.label_picoharp_res.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_picoharp_res.setObjectName("label_picoharp_res")
        self.label_picoharp_acqtime = QtWidgets.QLabel(self.groupBox_acq)
        self.label_picoharp_acqtime.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_picoharp_acqtime.setObjectName("label_picoharp_acqtime")
        self.int_picoharp_offset = QtWidgets.QSpinBox(self.groupBox_acq)
        self.int_picoharp_offset.setGeometry(QtCore.QRect(80, 40, 61, 22))
        self.int_picoharp_offset.setKeyboardTracking(False)
        self.int_picoharp_offset.setMaximum(100000)
        self.int_picoharp_offset.setSingleStep(10)
        self.int_picoharp_offset.setObjectName("int_picoharp_offset")
        self.label_picoharp_offset = QtWidgets.QLabel(self.groupBox_acq)
        self.label_picoharp_offset.setGeometry(QtCore.QRect(80, 20, 61, 16))
        self.label_picoharp_offset.setObjectName("label_picoharp_offset")
        self.btn_picoharp_start = QtWidgets.QPushButton(self.groupBox_acq)
        self.btn_picoharp_start.setGeometry(QtCore.QRect(10, 120, 51, 21))
        self.btn_picoharp_start.setObjectName("btn_picoharp_start")
        self.btn_picoharp_stop = QtWidgets.QPushButton(self.groupBox_acq)
        self.btn_picoharp_stop.setGeometry(QtCore.QRect(90, 120, 51, 21))
        self.btn_picoharp_stop.setObjectName("btn_picoharp_stop")
        self.label_picoharp_remaining = QtWidgets.QLabel(self.groupBox_acq)
        self.label_picoharp_remaining.setGeometry(QtCore.QRect(80, 90, 61, 22))
        self.label_picoharp_remaining.setObjectName("label_picoharp_remaining")
        self.cbox_picoharp_mode = QtWidgets.QComboBox(self.groupBox_acq)
        self.cbox_picoharp_mode.setGeometry(QtCore.QRect(48, 150, 91, 22))
        self.cbox_picoharp_mode.setObjectName("cbox_picoharp_mode")
        self.label_picoharp_nide = QtWidgets.QLabel(self.groupBox_acq)
        self.label_picoharp_nide.setGeometry(QtCore.QRect(10, 150, 41, 22))
        self.label_picoharp_nide.setObjectName("label_picoharp_nide")
        self.cbox_picoharp_res_acq = QtWidgets.QComboBox(self.groupBox_acq)
        self.cbox_picoharp_res_acq.setGeometry(QtCore.QRect(10, 40, 51, 22))
        self.cbox_picoharp_res_acq.setObjectName("cbox_picoharp_res_acq")
        self.btn_picoharp_connect = QtWidgets.QPushButton(Form)
        self.btn_picoharp_connect.setGeometry(QtCore.QRect(20, 420, 71, 21))
        self.btn_picoharp_connect.setCheckable(True)
        self.btn_picoharp_connect.setObjectName("btn_picoharp_connect")
        self.label_picoharp_status = QtWidgets.QLabel(Form)
        self.label_picoharp_status.setGeometry(QtCore.QRect(100, 420, 151, 20))
        self.label_picoharp_status.setObjectName("label_picoharp_status")
        self.chkbx_picoharp_autosave = QtWidgets.QCheckBox(Form)
        self.chkbx_picoharp_autosave.setGeometry(QtCore.QRect(430, 240, 70, 17))
        self.chkbx_picoharp_autosave.setObjectName("chkbx_picoharp_autosave")
        self.label_picoharp_filename = QtWidgets.QLabel(Form)
        self.label_picoharp_filename.setGeometry(QtCore.QRect(20, 240, 251, 16))
        self.label_picoharp_filename.setObjectName("label_picoharp_filename")
        self.chkbx_picoharp_autotrack = QtWidgets.QCheckBox(Form)
        self.chkbx_picoharp_autotrack.setGeometry(QtCore.QRect(350, 240, 70, 17))
        self.chkbx_picoharp_autotrack.setObjectName("chkbx_picoharp_autotrack")
        self.groupBox_disp = QtWidgets.QGroupBox(Form)
        self.groupBox_disp.setGeometry(QtCore.QRect(420, 260, 131, 181))
        self.groupBox_disp.setObjectName("groupBox_disp")
        self.cbox_picoharp_res_disp = QtWidgets.QComboBox(self.groupBox_disp)
        self.cbox_picoharp_res_disp.setGeometry(QtCore.QRect(10, 40, 61, 22))
        self.cbox_picoharp_res_disp.setObjectName("cbox_picoharp_res_disp")
        self.label_picoharp_res_disp = QtWidgets.QLabel(self.groupBox_disp)
        self.label_picoharp_res_disp.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_picoharp_res_disp.setObjectName("label_picoharp_res_disp")
        self.dbl_picoharp_disp_xmax = QtWidgets.QDoubleSpinBox(self.groupBox_disp)
        self.dbl_picoharp_disp_xmax.setGeometry(QtCore.QRect(10, 150, 101, 22))
        self.dbl_picoharp_disp_xmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_picoharp_disp_xmax.setKeyboardTracking(False)
        self.dbl_picoharp_disp_xmax.setDecimals(3)
        self.dbl_picoharp_disp_xmax.setMaximum(33554.432)
        self.dbl_picoharp_disp_xmax.setSingleStep(10.0)
        self.dbl_picoharp_disp_xmax.setObjectName("dbl_picoharp_disp_xmax")
        self.label_picoharp_disp_xmin = QtWidgets.QLabel(self.groupBox_disp)
        self.label_picoharp_disp_xmin.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_picoharp_disp_xmin.setObjectName("label_picoharp_disp_xmin")
        self.label_picoharp_disp_xmax = QtWidgets.QLabel(self.groupBox_disp)
        self.label_picoharp_disp_xmax.setGeometry(QtCore.QRect(10, 130, 61, 16))
        self.label_picoharp_disp_xmax.setObjectName("label_picoharp_disp_xmax")
        self.dbl_picoharp_disp_xmin = QtWidgets.QDoubleSpinBox(self.groupBox_disp)
        self.dbl_picoharp_disp_xmin.setGeometry(QtCore.QRect(10, 90, 101, 22))
        self.dbl_picoharp_disp_xmin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_picoharp_disp_xmin.setKeyboardTracking(False)
        self.dbl_picoharp_disp_xmin.setDecimals(3)
        self.dbl_picoharp_disp_xmin.setMaximum(33554.432)
        self.dbl_picoharp_disp_xmin.setSingleStep(10.0)
        self.dbl_picoharp_disp_xmin.setObjectName("dbl_picoharp_disp_xmin")
        self.chkbx_picoharp_disp_autoscale = QtWidgets.QCheckBox(self.groupBox_disp)
        self.chkbx_picoharp_disp_autoscale.setGeometry(QtCore.QRect(100, 40, 22, 22))
        self.chkbx_picoharp_disp_autoscale.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkbx_picoharp_disp_autoscale.setText("")
        self.chkbx_picoharp_disp_autoscale.setObjectName("chkbx_picoharp_disp_autoscale")
        self.label_picoharp_disp_autoscale = QtWidgets.QLabel(self.groupBox_disp)
        self.label_picoharp_disp_autoscale.setGeometry(QtCore.QRect(80, 20, 61, 16))
        self.label_picoharp_disp_autoscale.setObjectName("label_picoharp_disp_autoscale")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.glw_picoharp, self.btn_picoharp_connect)
        Form.setTabOrder(self.btn_picoharp_connect, self.int_picoharp_ZeroCr0)
        Form.setTabOrder(self.int_picoharp_ZeroCr0, self.int_picoharp_Discr0)
        Form.setTabOrder(self.int_picoharp_Discr0, self.int_picoharp_offset0)
        Form.setTabOrder(self.int_picoharp_offset0, self.int_picoharp_ZeroCr1)
        Form.setTabOrder(self.int_picoharp_ZeroCr1, self.int_picoharp_Discr1)
        Form.setTabOrder(self.int_picoharp_Discr1, self.btn_picoharp_update_settings)
        Form.setTabOrder(self.btn_picoharp_update_settings, self.cbox_picoharp_res_acq)
        Form.setTabOrder(self.cbox_picoharp_res_acq, self.int_picoharp_offset)
        Form.setTabOrder(self.int_picoharp_offset, self.int_picoharp_acqtime)
        Form.setTabOrder(self.int_picoharp_acqtime, self.btn_picoharp_start)
        Form.setTabOrder(self.btn_picoharp_start, self.btn_picoharp_stop)
        Form.setTabOrder(self.btn_picoharp_stop, self.cbox_picoharp_mode)
        Form.setTabOrder(self.cbox_picoharp_mode, self.chkbx_picoharp_autotrack)
        Form.setTabOrder(self.chkbx_picoharp_autotrack, self.chkbx_picoharp_autosave)
        Form.setTabOrder(self.chkbx_picoharp_autosave, self.btn_picoharp_save)
        Form.setTabOrder(self.btn_picoharp_save, self.cbox_picoharp_res_disp)
        Form.setTabOrder(self.cbox_picoharp_res_disp, self.dbl_picoharp_disp_xmin)
        Form.setTabOrder(self.dbl_picoharp_disp_xmin, self.dbl_picoharp_disp_xmax)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Picoharp"))
        self.btn_picoharp_save.setText(_translate("Form", "save"))
        self.groupBox_ch0.setTitle(_translate("Form", "Ch0 / Sync"))
        self.label_picoharp_ZeroCr0.setText(_translate("Form", "ZeroCr (mV)"))
        self.label_picoharp_Discr0.setText(_translate("Form", "Discr (mV)"))
        self.label_picoharp_offset0.setText(_translate("Form", "Offset (ps)"))
        self.label_picoharp_rate0.setText(_translate("Form", "rate0"))
        self.btn_picoharp_update_settings.setText(_translate("Form", "Apply"))
        self.groupBox_ch1.setTitle(_translate("Form", "Ch1"))
        self.label_picoharp_ZeroCr1.setText(_translate("Form", "ZeroCr (mV)"))
        self.label_picoharp_Discr1.setText(_translate("Form", "Discr (mV)"))
        self.label_picoharp_rate1.setText(_translate("Form", "rate1"))
        self.groupBox_acq.setTitle(_translate("Form", "Acquisition"))
        self.label_picoharp_res.setText(_translate("Form", "Res. (ps)"))
        self.label_picoharp_acqtime.setText(_translate("Form", "Time (s)"))
        self.label_picoharp_offset.setText(_translate("Form", "Offset (ns)"))
        self.btn_picoharp_start.setText(_translate("Form", "Start"))
        self.btn_picoharp_stop.setText(_translate("Form", "Stop"))
        self.label_picoharp_remaining.setText(_translate("Form", "label_picoharp_remaining"))
        self.label_picoharp_nide.setText(_translate("Form", "mode"))
        self.btn_picoharp_connect.setText(_translate("Form", "Connect"))
        self.label_picoharp_status.setText(_translate("Form", "picoharp status"))
        self.chkbx_picoharp_autosave.setText(_translate("Form", "autosave"))
        self.label_picoharp_filename.setText(_translate("Form", "label_picoharp_filename"))
        self.chkbx_picoharp_autotrack.setText(_translate("Form", "autotrack"))
        self.groupBox_disp.setTitle(_translate("Form", "Display"))
        self.label_picoharp_res_disp.setText(_translate("Form", "Disp. res."))
        self.label_picoharp_disp_xmin.setText(_translate("Form", "X min (ns)"))
        self.label_picoharp_disp_xmax.setText(_translate("Form", "X max (ns)"))
        self.label_picoharp_disp_autoscale.setText(_translate("Form", "Autoscale"))


from pyqtgraph import GraphicsLayoutWidget
