# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_tracker.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(389, 310)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.btn_tracker_driveleft = QtWidgets.QPushButton(Form)
        self.btn_tracker_driveleft.setGeometry(QtCore.QRect(30, 40, 21, 23))
        self.btn_tracker_driveleft.setObjectName("btn_tracker_driveleft")
        self.btn_tracker_driveright = QtWidgets.QPushButton(Form)
        self.btn_tracker_driveright.setGeometry(QtCore.QRect(70, 40, 21, 23))
        self.btn_tracker_driveright.setObjectName("btn_tracker_driveright")
        self.btn_tracker_driveup = QtWidgets.QPushButton(Form)
        self.btn_tracker_driveup.setGeometry(QtCore.QRect(50, 20, 21, 23))
        self.btn_tracker_driveup.setObjectName("btn_tracker_driveup")
        self.btn_tracker_drivedown = QtWidgets.QPushButton(Form)
        self.btn_tracker_drivedown.setGeometry(QtCore.QRect(50, 60, 21, 23))
        self.btn_tracker_drivedown.setObjectName("btn_tracker_drivedown")
        self.btn_tracker_drivezup = QtWidgets.QPushButton(Form)
        self.btn_tracker_drivezup.setGeometry(QtCore.QRect(150, 40, 21, 23))
        self.btn_tracker_drivezup.setObjectName("btn_tracker_drivezup")
        self.btn_tracker_drivezdown = QtWidgets.QPushButton(Form)
        self.btn_tracker_drivezdown.setGeometry(QtCore.QRect(150, 60, 21, 23))
        self.btn_tracker_drivezdown.setObjectName("btn_tracker_drivezdown")
        self.dbl_tracker_xystep = QtWidgets.QDoubleSpinBox(Form)
        self.dbl_tracker_xystep.setGeometry(QtCore.QRect(50, 100, 51, 22))
        self.dbl_tracker_xystep.setObjectName("dbl_tracker_xystep")
        self.dbl_tracker_zstep = QtWidgets.QDoubleSpinBox(Form)
        self.dbl_tracker_zstep.setGeometry(QtCore.QRect(140, 100, 51, 22))
        self.dbl_tracker_zstep.setObjectName("dbl_tracker_zstep")
        self.label_tracker_xystep = QtWidgets.QLabel(Form)
        self.label_tracker_xystep.setGeometry(QtCore.QRect(10, 100, 41, 22))
        self.label_tracker_xystep.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tracker_xystep.setObjectName("label_tracker_xystep")
        self.label_tracker_zstep = QtWidgets.QLabel(Form)
        self.label_tracker_zstep.setGeometry(QtCore.QRect(100, 100, 41, 22))
        self.label_tracker_zstep.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tracker_zstep.setObjectName("label_tracker_zstep")
        self.label_tracker_xrng = QtWidgets.QLabel(Form)
        self.label_tracker_xrng.setGeometry(QtCore.QRect(40, 130, 81, 22))
        self.label_tracker_xrng.setObjectName("label_tracker_xrng")
        self.dbl_tracker_xrng = QtWidgets.QDoubleSpinBox(Form)
        self.dbl_tracker_xrng.setGeometry(QtCore.QRect(110, 130, 51, 22))
        self.dbl_tracker_xrng.setObjectName("dbl_tracker_xrng")
        self.label_tracker_yrng = QtWidgets.QLabel(Form)
        self.label_tracker_yrng.setGeometry(QtCore.QRect(40, 160, 71, 22))
        self.label_tracker_yrng.setObjectName("label_tracker_yrng")
        self.dbl_tracker_yrng = QtWidgets.QDoubleSpinBox(Form)
        self.dbl_tracker_yrng.setGeometry(QtCore.QRect(110, 160, 51, 22))
        self.dbl_tracker_yrng.setObjectName("dbl_tracker_yrng")
        self.label_tracker_zrng = QtWidgets.QLabel(Form)
        self.label_tracker_zrng.setGeometry(QtCore.QRect(40, 190, 71, 22))
        self.label_tracker_zrng.setObjectName("label_tracker_zrng")
        self.dbl_tracker_zrng = QtWidgets.QDoubleSpinBox(Form)
        self.dbl_tracker_zrng.setGeometry(QtCore.QRect(110, 190, 51, 22))
        self.dbl_tracker_zrng.setObjectName("dbl_tracker_zrng")
        self.label_tracker_numdivs = QtWidgets.QLabel(Form)
        self.label_tracker_numdivs.setGeometry(QtCore.QRect(40, 220, 61, 22))
        self.label_tracker_numdivs.setObjectName("label_tracker_numdivs")
        self.int_tracker_numdivs = QtWidgets.QSpinBox(Form)
        self.int_tracker_numdivs.setGeometry(QtCore.QRect(110, 220, 51, 22))
        self.int_tracker_numdivs.setObjectName("int_tracker_numdivs")
        self.label_tracler_acqtime = QtWidgets.QLabel(Form)
        self.label_tracler_acqtime.setGeometry(QtCore.QRect(40, 250, 71, 22))
        self.label_tracler_acqtime.setObjectName("label_tracler_acqtime")
        self.dbl_tracker_acqtime = QtWidgets.QDoubleSpinBox(Form)
        self.dbl_tracker_acqtime.setGeometry(QtCore.QRect(110, 250, 51, 22))
        self.dbl_tracker_acqtime.setObjectName("dbl_tracker_acqtime")
        self.chkbx_tracker_flip = QtWidgets.QCheckBox(Form)
        self.chkbx_tracker_flip.setGeometry(QtCore.QRect(120, 10, 70, 17))
        self.chkbx_tracker_flip.setObjectName("chkbx_tracker_flip")
        self.dbl_tracker_pltime = QtWidgets.QDoubleSpinBox(Form)
        self.dbl_tracker_pltime.setGeometry(QtCore.QRect(110, 280, 51, 22))
        self.dbl_tracker_pltime.setObjectName("dbl_tracker_pltime")
        self.label_tracker_pltime = QtWidgets.QLabel(Form)
        self.label_tracker_pltime.setGeometry(QtCore.QRect(40, 280, 71, 22))
        self.label_tracker_pltime.setObjectName("label_tracker_pltime")
        self.groupBox_tracker_freq = QtWidgets.QGroupBox(Form)
        self.groupBox_tracker_freq.setGeometry(QtCore.QRect(210, 10, 171, 291))
        self.groupBox_tracker_freq.setObjectName("groupBox_tracker_freq")
        self.label_tracler_freq_acqtime = QtWidgets.QLabel(self.groupBox_tracker_freq)
        self.label_tracler_freq_acqtime.setGeometry(QtCore.QRect(40, 260, 71, 22))
        self.label_tracler_freq_acqtime.setObjectName("label_tracler_freq_acqtime")
        self.label_tracker_freq_numdivs = QtWidgets.QLabel(self.groupBox_tracker_freq)
        self.label_tracker_freq_numdivs.setGeometry(QtCore.QRect(40, 230, 61, 22))
        self.label_tracker_freq_numdivs.setObjectName("label_tracker_freq_numdivs")
        self.dbl_tracker_freq_acqtime = QtWidgets.QDoubleSpinBox(self.groupBox_tracker_freq)
        self.dbl_tracker_freq_acqtime.setGeometry(QtCore.QRect(110, 260, 51, 22))
        self.dbl_tracker_freq_acqtime.setObjectName("dbl_tracker_freq_acqtime")
        self.int_tracker_freq_numdivs = QtWidgets.QSpinBox(self.groupBox_tracker_freq)
        self.int_tracker_freq_numdivs.setGeometry(QtCore.QRect(110, 230, 51, 22))
        self.int_tracker_freq_numdivs.setObjectName("int_tracker_freq_numdivs")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_tracker_freq)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 151, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_tracker_freq = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_tracker_freq.setContentsMargins(0, 0, 0, 0)
        self.grid_tracker_freq.setObjectName("grid_tracker_freq")
        self.dbl_tracker_acqtime.raise_()
        self.label_tracker_numdivs.raise_()
        self.int_tracker_numdivs.raise_()
        self.label_tracler_acqtime.raise_()
        self.label_tracler_freq_acqtime.raise_()
        self.label_tracker_freq_numdivs.raise_()
        self.dbl_tracker_freq_acqtime.raise_()
        self.int_tracker_freq_numdivs.raise_()
        self.gridLayoutWidget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.dbl_tracker_xystep, self.dbl_tracker_zstep)
        Form.setTabOrder(self.dbl_tracker_zstep, self.dbl_tracker_xrng)
        Form.setTabOrder(self.dbl_tracker_xrng, self.dbl_tracker_yrng)
        Form.setTabOrder(self.dbl_tracker_yrng, self.dbl_tracker_zrng)
        Form.setTabOrder(self.dbl_tracker_zrng, self.int_tracker_numdivs)
        Form.setTabOrder(self.int_tracker_numdivs, self.dbl_tracker_acqtime)
        Form.setTabOrder(self.dbl_tracker_acqtime, self.dbl_tracker_pltime)
        Form.setTabOrder(self.dbl_tracker_pltime, self.btn_tracker_driveup)
        Form.setTabOrder(self.btn_tracker_driveup, self.btn_tracker_driveright)
        Form.setTabOrder(self.btn_tracker_driveright, self.btn_tracker_drivedown)
        Form.setTabOrder(self.btn_tracker_drivedown, self.btn_tracker_driveleft)
        Form.setTabOrder(self.btn_tracker_driveleft, self.btn_tracker_drivezdown)
        Form.setTabOrder(self.btn_tracker_drivezdown, self.btn_tracker_drivezup)
        Form.setTabOrder(self.btn_tracker_drivezup, self.chkbx_tracker_flip)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Tracker Control"))
        self.btn_tracker_driveleft.setText(_translate("Form", "<"))
        self.btn_tracker_driveright.setText(_translate("Form", ">"))
        self.btn_tracker_driveup.setText(_translate("Form", "^"))
        self.btn_tracker_drivedown.setText(_translate("Form", "v"))
        self.btn_tracker_drivezup.setText(_translate("Form", "z+"))
        self.btn_tracker_drivezdown.setText(_translate("Form", "z-"))
        self.label_tracker_xystep.setText(_translate("Form", "xy step:"))
        self.label_tracker_zstep.setText(_translate("Form", "z step:"))
        self.label_tracker_xrng.setText(_translate("Form", "X range (um)"))
        self.label_tracker_yrng.setText(_translate("Form", "Y range (um)"))
        self.label_tracker_zrng.setText(_translate("Form", "Z range (um)"))
        self.label_tracker_numdivs.setText(_translate("Form", "# of steps"))
        self.label_tracler_acqtime.setText(_translate("Form", "Acq. Time (s)"))
        self.chkbx_tracker_flip.setText(_translate("Form", "Flip Mount"))
        self.label_tracker_pltime.setText(_translate("Form", "PL Meas. (s)"))
        self.groupBox_tracker_freq.setTitle(_translate("Form", "Frequency Tracking"))
        self.label_tracler_freq_acqtime.setText(_translate("Form", "Acq. Time (s)"))
        self.label_tracker_freq_numdivs.setText(_translate("Form", "# of steps"))


