# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_satcurve.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(428, 407)
        self.glw_satcurve = GraphicsLayoutWidget(Form)
        self.glw_satcurve.setGeometry(QtCore.QRect(10, 10, 411, 291))
        self.glw_satcurve.setObjectName("glw_satcurve")
        self.btn_satcurve_clear = QtWidgets.QPushButton(Form)
        self.btn_satcurve_clear.setGeometry(QtCore.QRect(10, 340, 41, 21))
        self.btn_satcurve_clear.setObjectName("btn_satcurve_clear")
        self.btn_satcurve_meas = QtWidgets.QPushButton(Form)
        self.btn_satcurve_meas.setGeometry(QtCore.QRect(50, 340, 41, 21))
        self.btn_satcurve_meas.setObjectName("btn_satcurve_meas")
        self.label_satcurve_acqtime = QtWidgets.QLabel(Form)
        self.label_satcurve_acqtime.setGeometry(QtCore.QRect(20, 370, 71, 20))
        self.label_satcurve_acqtime.setObjectName("label_satcurve_acqtime")
        self.dbl_satcurve_acqtime = QtWidgets.QDoubleSpinBox(Form)
        self.dbl_satcurve_acqtime.setGeometry(QtCore.QRect(90, 370, 51, 22))
        self.dbl_satcurve_acqtime.setDecimals(1)
        self.dbl_satcurve_acqtime.setMaximum(99.0)
        self.dbl_satcurve_acqtime.setObjectName("dbl_satcurve_acqtime")
        self.btn_satcurve_fit = QtWidgets.QPushButton(Form)
        self.btn_satcurve_fit.setGeometry(QtCore.QRect(350, 310, 61, 41))
        self.btn_satcurve_fit.setObjectName("btn_satcurve_fit")
        self.btn_satcurve_save = QtWidgets.QPushButton(Form)
        self.btn_satcurve_save.setGeometry(QtCore.QRect(350, 360, 61, 41))
        self.btn_satcurve_save.setObjectName("btn_satcurve_save")
        self.label_satcurve_fit = QtWidgets.QLabel(Form)
        self.label_satcurve_fit.setGeometry(QtCore.QRect(260, 180, 131, 61))
        self.label_satcurve_fit.setText("")
        self.label_satcurve_fit.setObjectName("label_satcurve_fit")
        self.chkbx_satcurve_beep = QtWidgets.QCheckBox(Form)
        self.chkbx_satcurve_beep.setGeometry(QtCore.QRect(90, 340, 51, 20))
        self.chkbx_satcurve_beep.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkbx_satcurve_beep.setObjectName("chkbx_satcurve_beep")
        self.groupBox_voa = QtWidgets.QGroupBox(Form)
        self.groupBox_voa.setGeometry(QtCore.QRect(160, 320, 181, 80))
        self.groupBox_voa.setObjectName("groupBox_voa")
        self.btn_satcurve_voa_start = QtWidgets.QPushButton(self.groupBox_voa)
        self.btn_satcurve_voa_start.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.btn_satcurve_voa_start.setObjectName("btn_satcurve_voa_start")
        self.dbl_satcurve_voa_start = QtWidgets.QDoubleSpinBox(self.groupBox_voa)
        self.dbl_satcurve_voa_start.setGeometry(QtCore.QRect(10, 50, 51, 22))
        self.dbl_satcurve_voa_start.setDecimals(1)
        self.dbl_satcurve_voa_start.setMaximum(5.0)
        self.dbl_satcurve_voa_start.setSingleStep(0.1)
        self.dbl_satcurve_voa_start.setObjectName("dbl_satcurve_voa_start")
        self.btn_satcurve_voa_stop = QtWidgets.QPushButton(self.groupBox_voa)
        self.btn_satcurve_voa_stop.setGeometry(QtCore.QRect(60, 20, 41, 21))
        self.btn_satcurve_voa_stop.setObjectName("btn_satcurve_voa_stop")
        self.dbl_satcurve_voa_stop = QtWidgets.QDoubleSpinBox(self.groupBox_voa)
        self.dbl_satcurve_voa_stop.setGeometry(QtCore.QRect(60, 50, 51, 22))
        self.dbl_satcurve_voa_stop.setDecimals(1)
        self.dbl_satcurve_voa_stop.setMaximum(5.0)
        self.dbl_satcurve_voa_stop.setSingleStep(0.1)
        self.dbl_satcurve_voa_stop.setObjectName("dbl_satcurve_voa_stop")
        self.int_satcurve_voa_numdivs = QtWidgets.QSpinBox(self.groupBox_voa)
        self.int_satcurve_voa_numdivs.setGeometry(QtCore.QRect(121, 50, 51, 22))
        self.int_satcurve_voa_numdivs.setMinimum(1)
        self.int_satcurve_voa_numdivs.setMaximum(1000)
        self.int_satcurve_voa_numdivs.setObjectName("int_satcurve_voa_numdivs")
        self.label_satcurve_voa_numdivs = QtWidgets.QLabel(self.groupBox_voa)
        self.label_satcurve_voa_numdivs.setGeometry(QtCore.QRect(100, 50, 20, 20))
        self.label_satcurve_voa_numdivs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_satcurve_voa_numdivs.setObjectName("label_satcurve_voa_numdivs")
        self.cbox_satcurve_voa = QtWidgets.QComboBox(self.groupBox_voa)
        self.cbox_satcurve_voa.setGeometry(QtCore.QRect(110, 20, 61, 22))
        self.cbox_satcurve_voa.setObjectName("cbox_satcurve_voa")
        self.cbox_satcurve_pm = QtWidgets.QComboBox(Form)
        self.cbox_satcurve_pm.setGeometry(QtCore.QRect(10, 310, 131, 22))
        self.cbox_satcurve_pm.setObjectName("cbox_satcurve_pm")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.glw_satcurve, self.cbox_satcurve_pm)
        Form.setTabOrder(self.cbox_satcurve_pm, self.btn_satcurve_clear)
        Form.setTabOrder(self.btn_satcurve_clear, self.btn_satcurve_meas)
        Form.setTabOrder(self.btn_satcurve_meas, self.chkbx_satcurve_beep)
        Form.setTabOrder(self.chkbx_satcurve_beep, self.dbl_satcurve_acqtime)
        Form.setTabOrder(self.dbl_satcurve_acqtime, self.dbl_satcurve_voa_start)
        Form.setTabOrder(self.dbl_satcurve_voa_start, self.dbl_satcurve_voa_stop)
        Form.setTabOrder(self.dbl_satcurve_voa_stop, self.int_satcurve_voa_numdivs)
        Form.setTabOrder(self.int_satcurve_voa_numdivs, self.btn_satcurve_voa_start)
        Form.setTabOrder(self.btn_satcurve_voa_start, self.btn_satcurve_voa_stop)
        Form.setTabOrder(self.btn_satcurve_voa_stop, self.cbox_satcurve_voa)
        Form.setTabOrder(self.cbox_satcurve_voa, self.btn_satcurve_fit)
        Form.setTabOrder(self.btn_satcurve_fit, self.btn_satcurve_save)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Saturation Curve Measurements"))
        self.btn_satcurve_clear.setText(_translate("Form", "clear"))
        self.btn_satcurve_meas.setText(_translate("Form", "meas"))
        self.label_satcurve_acqtime.setText(_translate("Form", "meas. time (s)"))
        self.btn_satcurve_fit.setText(_translate("Form", "fit"))
        self.btn_satcurve_save.setText(_translate("Form", "save"))
        self.chkbx_satcurve_beep.setText(_translate("Form", "beep"))
        self.groupBox_voa.setTitle(_translate("Form", "VOA Sweep"))
        self.btn_satcurve_voa_start.setText(_translate("Form", "start"))
        self.btn_satcurve_voa_stop.setText(_translate("Form", "stop"))
        self.label_satcurve_voa_numdivs.setText(_translate("Form", "x"))


from pyqtgraph import GraphicsLayoutWidget
