# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_calculator.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(551, 225)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.groupBox_NV = QtWidgets.QGroupBox(Form)
        self.groupBox_NV.setGeometry(QtCore.QRect(10, 10, 241, 201))
        self.groupBox_NV.setObjectName("groupBox_NV")
        self.btn_nvfreq_2 = QtWidgets.QPushButton(self.groupBox_NV)
        self.btn_nvfreq_2.setGeometry(QtCore.QRect(190, 170, 41, 22))
        self.btn_nvfreq_2.setObjectName("btn_nvfreq_2")
        self.label_Bz = QtWidgets.QLabel(self.groupBox_NV)
        self.label_Bz.setGeometry(QtCore.QRect(10, 20, 101, 22))
        self.label_Bz.setObjectName("label_Bz")
        self.label_nvfreq_2 = QtWidgets.QLabel(self.groupBox_NV)
        self.label_nvfreq_2.setGeometry(QtCore.QRect(10, 170, 101, 22))
        self.label_nvfreq_2.setObjectName("label_nvfreq_2")
        self.btn_nvfreq = QtWidgets.QPushButton(self.groupBox_NV)
        self.btn_nvfreq.setGeometry(QtCore.QRect(190, 50, 41, 22))
        self.btn_nvfreq.setObjectName("btn_nvfreq")
        self.label_deerfreq = QtWidgets.QLabel(self.groupBox_NV)
        self.label_deerfreq.setGeometry(QtCore.QRect(10, 80, 101, 22))
        self.label_deerfreq.setObjectName("label_deerfreq")
        self.dbl_calc_nvfreq = QtWidgets.QDoubleSpinBox(self.groupBox_NV)
        self.dbl_calc_nvfreq.setGeometry(QtCore.QRect(110, 50, 71, 22))
        self.dbl_calc_nvfreq.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dbl_calc_nvfreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_calc_nvfreq.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dbl_calc_nvfreq.setKeyboardTracking(False)
        self.dbl_calc_nvfreq.setDecimals(3)
        self.dbl_calc_nvfreq.setMinimum(-9999.0)
        self.dbl_calc_nvfreq.setMaximum(9999.0)
        self.dbl_calc_nvfreq.setObjectName("dbl_calc_nvfreq")
        self.btn_deerfreq = QtWidgets.QPushButton(self.groupBox_NV)
        self.btn_deerfreq.setGeometry(QtCore.QRect(190, 80, 41, 22))
        self.btn_deerfreq.setObjectName("btn_deerfreq")
        self.label_protonfreq = QtWidgets.QLabel(self.groupBox_NV)
        self.label_protonfreq.setGeometry(QtCore.QRect(10, 110, 101, 22))
        self.label_protonfreq.setObjectName("label_protonfreq")
        self.label_protontau = QtWidgets.QLabel(self.groupBox_NV)
        self.label_protontau.setGeometry(QtCore.QRect(10, 140, 101, 22))
        self.label_protontau.setObjectName("label_protontau")
        self.dbl_calc_Bz = QtWidgets.QDoubleSpinBox(self.groupBox_NV)
        self.dbl_calc_Bz.setGeometry(QtCore.QRect(110, 20, 71, 22))
        self.dbl_calc_Bz.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dbl_calc_Bz.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_calc_Bz.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dbl_calc_Bz.setKeyboardTracking(False)
        self.dbl_calc_Bz.setMinimum(-9999.0)
        self.dbl_calc_Bz.setMaximum(9999.0)
        self.dbl_calc_Bz.setObjectName("dbl_calc_Bz")
        self.dbl_calc_deerfreq = QtWidgets.QDoubleSpinBox(self.groupBox_NV)
        self.dbl_calc_deerfreq.setGeometry(QtCore.QRect(110, 80, 71, 22))
        self.dbl_calc_deerfreq.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dbl_calc_deerfreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_calc_deerfreq.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dbl_calc_deerfreq.setKeyboardTracking(False)
        self.dbl_calc_deerfreq.setDecimals(3)
        self.dbl_calc_deerfreq.setMinimum(-9999.0)
        self.dbl_calc_deerfreq.setMaximum(9999.0)
        self.dbl_calc_deerfreq.setObjectName("dbl_calc_deerfreq")
        self.label_nvfreq = QtWidgets.QLabel(self.groupBox_NV)
        self.label_nvfreq.setGeometry(QtCore.QRect(10, 50, 101, 22))
        self.label_nvfreq.setObjectName("label_nvfreq")
        self.dbl_calc_protonfreq = QtWidgets.QDoubleSpinBox(self.groupBox_NV)
        self.dbl_calc_protonfreq.setGeometry(QtCore.QRect(110, 110, 71, 22))
        self.dbl_calc_protonfreq.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dbl_calc_protonfreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_calc_protonfreq.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dbl_calc_protonfreq.setKeyboardTracking(False)
        self.dbl_calc_protonfreq.setDecimals(3)
        self.dbl_calc_protonfreq.setMinimum(-9999.0)
        self.dbl_calc_protonfreq.setMaximum(9999.0)
        self.dbl_calc_protonfreq.setObjectName("dbl_calc_protonfreq")
        self.dbl_calc_protontau = QtWidgets.QDoubleSpinBox(self.groupBox_NV)
        self.dbl_calc_protontau.setGeometry(QtCore.QRect(110, 140, 71, 22))
        self.dbl_calc_protontau.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dbl_calc_protontau.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_calc_protontau.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dbl_calc_protontau.setKeyboardTracking(False)
        self.dbl_calc_protontau.setDecimals(3)
        self.dbl_calc_protontau.setMinimum(-9999.0)
        self.dbl_calc_protontau.setMaximum(9999.0)
        self.dbl_calc_protontau.setObjectName("dbl_calc_protontau")
        self.dbl_calc_nvfreq_2 = QtWidgets.QDoubleSpinBox(self.groupBox_NV)
        self.dbl_calc_nvfreq_2.setGeometry(QtCore.QRect(110, 170, 71, 22))
        self.dbl_calc_nvfreq_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dbl_calc_nvfreq_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_calc_nvfreq_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dbl_calc_nvfreq_2.setKeyboardTracking(False)
        self.dbl_calc_nvfreq_2.setDecimals(3)
        self.dbl_calc_nvfreq_2.setMinimum(-9999.0)
        self.dbl_calc_nvfreq_2.setMaximum(9999.0)
        self.dbl_calc_nvfreq_2.setObjectName("dbl_calc_nvfreq_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(260, 10, 281, 201))
        self.groupBox.setObjectName("groupBox")
        self.label_calc_temp = QtWidgets.QLabel(self.groupBox)
        self.label_calc_temp.setGeometry(QtCore.QRect(10, 140, 101, 22))
        self.label_calc_temp.setObjectName("label_calc_temp")
        self.label_calc_energy = QtWidgets.QLabel(self.groupBox)
        self.label_calc_energy.setGeometry(QtCore.QRect(10, 80, 101, 22))
        self.label_calc_energy.setObjectName("label_calc_energy")
        self.label_calc_freq = QtWidgets.QLabel(self.groupBox)
        self.label_calc_freq.setGeometry(QtCore.QRect(10, 110, 101, 22))
        self.label_calc_freq.setObjectName("label_calc_freq")
        self.label_calc_wavelength = QtWidgets.QLabel(self.groupBox)
        self.label_calc_wavelength.setGeometry(QtCore.QRect(10, 50, 101, 22))
        self.label_calc_wavelength.setObjectName("label_calc_wavelength")
        self.label_label_calc_abs = QtWidgets.QLabel(self.groupBox)
        self.label_label_calc_abs.setGeometry(QtCore.QRect(100, 20, 81, 22))
        self.label_label_calc_abs.setAlignment(QtCore.Qt.AlignCenter)
        self.label_label_calc_abs.setObjectName("label_label_calc_abs")
        self.dbl_calc_energy_abs = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dbl_calc_energy_abs.setGeometry(QtCore.QRect(100, 80, 81, 22))
        self.dbl_calc_energy_abs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dbl_calc_energy_abs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_calc_energy_abs.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dbl_calc_energy_abs.setKeyboardTracking(False)
        self.dbl_calc_energy_abs.setDecimals(4)
        self.dbl_calc_energy_abs.setMinimum(0.0)
        self.dbl_calc_energy_abs.setMaximum(20000.0)
        self.dbl_calc_energy_abs.setObjectName("dbl_calc_energy_abs")
        self.dbl_calc_freq_abs = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dbl_calc_freq_abs.setGeometry(QtCore.QRect(100, 110, 81, 22))
        self.dbl_calc_freq_abs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dbl_calc_freq_abs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_calc_freq_abs.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dbl_calc_freq_abs.setKeyboardTracking(False)
        self.dbl_calc_freq_abs.setDecimals(4)
        self.dbl_calc_freq_abs.setMinimum(0.0)
        self.dbl_calc_freq_abs.setMaximum(1000000.0)
        self.dbl_calc_freq_abs.setObjectName("dbl_calc_freq_abs")
        self.dbl_calc_temp_abs = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dbl_calc_temp_abs.setGeometry(QtCore.QRect(100, 140, 81, 22))
        self.dbl_calc_temp_abs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dbl_calc_temp_abs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_calc_temp_abs.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dbl_calc_temp_abs.setKeyboardTracking(False)
        self.dbl_calc_temp_abs.setDecimals(3)
        self.dbl_calc_temp_abs.setMinimum(0.0)
        self.dbl_calc_temp_abs.setMaximum(1000000.0)
        self.dbl_calc_temp_abs.setObjectName("dbl_calc_temp_abs")
        self.dbl_calc_wavelength_abs = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dbl_calc_wavelength_abs.setGeometry(QtCore.QRect(100, 50, 81, 22))
        self.dbl_calc_wavelength_abs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dbl_calc_wavelength_abs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_calc_wavelength_abs.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dbl_calc_wavelength_abs.setKeyboardTracking(False)
        self.dbl_calc_wavelength_abs.setDecimals(4)
        self.dbl_calc_wavelength_abs.setMinimum(0.0)
        self.dbl_calc_wavelength_abs.setMaximum(10000.0)
        self.dbl_calc_wavelength_abs.setObjectName("dbl_calc_wavelength_abs")
        self.label_calc_delta = QtWidgets.QLabel(self.groupBox)
        self.label_calc_delta.setGeometry(QtCore.QRect(190, 20, 81, 22))
        self.label_calc_delta.setAlignment(QtCore.Qt.AlignCenter)
        self.label_calc_delta.setObjectName("label_calc_delta")
        self.dbl_calc_freq_delta = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dbl_calc_freq_delta.setGeometry(QtCore.QRect(190, 110, 81, 22))
        self.dbl_calc_freq_delta.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dbl_calc_freq_delta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_calc_freq_delta.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dbl_calc_freq_delta.setKeyboardTracking(False)
        self.dbl_calc_freq_delta.setDecimals(4)
        self.dbl_calc_freq_delta.setMinimum(-1000.0)
        self.dbl_calc_freq_delta.setMaximum(1000.0)
        self.dbl_calc_freq_delta.setObjectName("dbl_calc_freq_delta")
        self.dbl_calc_temp_delta = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dbl_calc_temp_delta.setGeometry(QtCore.QRect(190, 140, 81, 22))
        self.dbl_calc_temp_delta.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dbl_calc_temp_delta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_calc_temp_delta.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dbl_calc_temp_delta.setKeyboardTracking(False)
        self.dbl_calc_temp_delta.setDecimals(3)
        self.dbl_calc_temp_delta.setMinimum(-9999.0)
        self.dbl_calc_temp_delta.setMaximum(9999.0)
        self.dbl_calc_temp_delta.setObjectName("dbl_calc_temp_delta")
        self.dbl_calc_energy_delta = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dbl_calc_energy_delta.setGeometry(QtCore.QRect(190, 80, 81, 22))
        self.dbl_calc_energy_delta.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dbl_calc_energy_delta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_calc_energy_delta.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dbl_calc_energy_delta.setKeyboardTracking(False)
        self.dbl_calc_energy_delta.setDecimals(4)
        self.dbl_calc_energy_delta.setMinimum(-20000.0)
        self.dbl_calc_energy_delta.setMaximum(20000.0)
        self.dbl_calc_energy_delta.setProperty("value", 0.0)
        self.dbl_calc_energy_delta.setObjectName("dbl_calc_energy_delta")
        self.dbl_calc_wavelength_delta = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dbl_calc_wavelength_delta.setGeometry(QtCore.QRect(190, 50, 81, 22))
        self.dbl_calc_wavelength_delta.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dbl_calc_wavelength_delta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbl_calc_wavelength_delta.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dbl_calc_wavelength_delta.setKeyboardTracking(False)
        self.dbl_calc_wavelength_delta.setDecimals(4)
        self.dbl_calc_wavelength_delta.setMinimum(-10000.0)
        self.dbl_calc_wavelength_delta.setMaximum(10000.0)
        self.dbl_calc_wavelength_delta.setObjectName("dbl_calc_wavelength_delta")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.dbl_calc_Bz, self.dbl_calc_nvfreq)
        Form.setTabOrder(self.dbl_calc_nvfreq, self.dbl_calc_deerfreq)
        Form.setTabOrder(self.dbl_calc_deerfreq, self.dbl_calc_protonfreq)
        Form.setTabOrder(self.dbl_calc_protonfreq, self.dbl_calc_protontau)
        Form.setTabOrder(self.dbl_calc_protontau, self.dbl_calc_nvfreq_2)
        Form.setTabOrder(self.dbl_calc_nvfreq_2, self.btn_nvfreq)
        Form.setTabOrder(self.btn_nvfreq, self.btn_deerfreq)
        Form.setTabOrder(self.btn_deerfreq, self.btn_nvfreq_2)
        Form.setTabOrder(self.btn_nvfreq_2, self.dbl_calc_wavelength_abs)
        Form.setTabOrder(self.dbl_calc_wavelength_abs, self.dbl_calc_energy_abs)
        Form.setTabOrder(self.dbl_calc_energy_abs, self.dbl_calc_freq_abs)
        Form.setTabOrder(self.dbl_calc_freq_abs, self.dbl_calc_temp_abs)
        Form.setTabOrder(self.dbl_calc_temp_abs, self.dbl_calc_wavelength_delta)
        Form.setTabOrder(self.dbl_calc_wavelength_delta, self.dbl_calc_energy_delta)
        Form.setTabOrder(self.dbl_calc_energy_delta, self.dbl_calc_freq_delta)
        Form.setTabOrder(self.dbl_calc_freq_delta, self.dbl_calc_temp_delta)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.groupBox_NV.setTitle(_translate("Form", "NV Parameters"))
        self.btn_nvfreq_2.setText(_translate("Form", "get"))
        self.label_Bz.setText(_translate("Form", "Bz (G)"))
        self.label_nvfreq_2.setText(_translate("Form", "NV Freq +1 (MHz)"))
        self.btn_nvfreq.setText(_translate("Form", "get"))
        self.label_deerfreq.setText(_translate("Form", "DEER Freq (MHz)"))
        self.btn_deerfreq.setText(_translate("Form", "get"))
        self.label_protonfreq.setText(_translate("Form", "Proton Freq (kHz)"))
        self.label_protontau.setText(_translate("Form", "Proton tau (ns)"))
        self.label_nvfreq.setText(_translate("Form", "NV Freq -1 (MHz)"))
        self.groupBox.setTitle(_translate("Form", "Photon Unit Conversion"))
        self.label_calc_temp.setText(_translate("Form", "Temperature (K)"))
        self.label_calc_energy.setText(_translate("Form", "Energy (meV)"))
        self.label_calc_freq.setText(_translate("Form", "Frequency (GHz)"))
        self.label_calc_wavelength.setText(_translate("Form", "Wavelength (nm)"))
        self.label_label_calc_abs.setText(_translate("Form", "Absolute"))
        self.label_calc_delta.setText(_translate("Form", "Delta"))

