# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_shortcuts.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(702, 199)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.label_shortcuts_name = QtWidgets.QLabel(Form)
        self.label_shortcuts_name.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_shortcuts_name.setObjectName("label_shortcuts_name")
        self.label_shortcuts_command = QtWidgets.QLabel(Form)
        self.label_shortcuts_command.setGeometry(QtCore.QRect(140, 10, 47, 13))
        self.label_shortcuts_command.setObjectName("label_shortcuts_command")
        self.linein_shortcuts_1 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_1.setGeometry(QtCore.QRect(10, 30, 113, 20))
        self.linein_shortcuts_1.setObjectName("linein_shortcuts_1")
        self.linein_shortcuts_2 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_2.setGeometry(QtCore.QRect(10, 50, 113, 20))
        self.linein_shortcuts_2.setObjectName("linein_shortcuts_2")
        self.linein_shortcuts_3 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_3.setGeometry(QtCore.QRect(10, 70, 113, 20))
        self.linein_shortcuts_3.setObjectName("linein_shortcuts_3")
        self.linein_shortcuts_4 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_4.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.linein_shortcuts_4.setObjectName("linein_shortcuts_4")
        self.linein_shortcuts_5 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_5.setGeometry(QtCore.QRect(10, 110, 113, 20))
        self.linein_shortcuts_5.setObjectName("linein_shortcuts_5")
        self.linein_shortcuts_6 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_6.setGeometry(QtCore.QRect(10, 130, 113, 20))
        self.linein_shortcuts_6.setObjectName("linein_shortcuts_6")
        self.linein_shortcuts_7 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_7.setGeometry(QtCore.QRect(10, 150, 113, 20))
        self.linein_shortcuts_7.setObjectName("linein_shortcuts_7")
        self.linein_shortcuts_8 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_8.setGeometry(QtCore.QRect(10, 170, 113, 20))
        self.linein_shortcuts_8.setObjectName("linein_shortcuts_8")
        self.linein_shortcuts_command_1 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_command_1.setGeometry(QtCore.QRect(140, 30, 551, 20))
        self.linein_shortcuts_command_1.setObjectName("linein_shortcuts_command_1")
        self.linein_shortcuts_command_2 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_command_2.setGeometry(QtCore.QRect(140, 50, 551, 20))
        self.linein_shortcuts_command_2.setObjectName("linein_shortcuts_command_2")
        self.linein_shortcuts_command_3 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_command_3.setGeometry(QtCore.QRect(140, 70, 551, 20))
        self.linein_shortcuts_command_3.setObjectName("linein_shortcuts_command_3")
        self.linein_shortcuts_command_4 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_command_4.setGeometry(QtCore.QRect(140, 90, 551, 20))
        self.linein_shortcuts_command_4.setObjectName("linein_shortcuts_command_4")
        self.linein_shortcuts_command_5 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_command_5.setGeometry(QtCore.QRect(140, 110, 551, 20))
        self.linein_shortcuts_command_5.setObjectName("linein_shortcuts_command_5")
        self.linein_shortcuts_command_6 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_command_6.setGeometry(QtCore.QRect(140, 130, 551, 20))
        self.linein_shortcuts_command_6.setObjectName("linein_shortcuts_command_6")
        self.linein_shortcuts_command_7 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_command_7.setGeometry(QtCore.QRect(140, 150, 551, 20))
        self.linein_shortcuts_command_7.setObjectName("linein_shortcuts_command_7")
        self.linein_shortcuts_command_8 = QtWidgets.QLineEdit(Form)
        self.linein_shortcuts_command_8.setGeometry(QtCore.QRect(140, 170, 551, 20))
        self.linein_shortcuts_command_8.setObjectName("linein_shortcuts_command_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.linein_shortcuts_1, self.linein_shortcuts_command_1)
        Form.setTabOrder(self.linein_shortcuts_command_1, self.linein_shortcuts_2)
        Form.setTabOrder(self.linein_shortcuts_2, self.linein_shortcuts_command_2)
        Form.setTabOrder(self.linein_shortcuts_command_2, self.linein_shortcuts_3)
        Form.setTabOrder(self.linein_shortcuts_3, self.linein_shortcuts_command_3)
        Form.setTabOrder(self.linein_shortcuts_command_3, self.linein_shortcuts_4)
        Form.setTabOrder(self.linein_shortcuts_4, self.linein_shortcuts_command_4)
        Form.setTabOrder(self.linein_shortcuts_command_4, self.linein_shortcuts_5)
        Form.setTabOrder(self.linein_shortcuts_5, self.linein_shortcuts_command_5)
        Form.setTabOrder(self.linein_shortcuts_command_5, self.linein_shortcuts_6)
        Form.setTabOrder(self.linein_shortcuts_6, self.linein_shortcuts_command_6)
        Form.setTabOrder(self.linein_shortcuts_command_6, self.linein_shortcuts_7)
        Form.setTabOrder(self.linein_shortcuts_7, self.linein_shortcuts_command_7)
        Form.setTabOrder(self.linein_shortcuts_command_7, self.linein_shortcuts_8)
        Form.setTabOrder(self.linein_shortcuts_8, self.linein_shortcuts_command_8)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Shortcuts"))
        self.label_shortcuts_name.setText(_translate("Form", "Name"))
        self.label_shortcuts_command.setText(_translate("Form", "Command"))

