# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_batch.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(484, 370)
        self.btn_nvlist_stop = QtWidgets.QPushButton(Form)
        self.btn_nvlist_stop.setGeometry(QtCore.QRect(410, 10, 71, 31))
        self.btn_nvlist_stop.setObjectName("btn_nvlist_stop")
        self.btn_nvlist_drive = QtWidgets.QPushButton(Form)
        self.btn_nvlist_drive.setGeometry(QtCore.QRect(280, 10, 51, 31))
        self.btn_nvlist_drive.setObjectName("btn_nvlist_drive")
        self.btn_nvlist_start = QtWidgets.QPushButton(Form)
        self.btn_nvlist_start.setGeometry(QtCore.QRect(340, 10, 71, 31))
        self.btn_nvlist_start.setObjectName("btn_nvlist_start")
        self.groupBox_nvlist = QtWidgets.QGroupBox(Form)
        self.groupBox_nvlist.setGeometry(QtCore.QRect(10, 10, 261, 351))
        self.groupBox_nvlist.setObjectName("groupBox_nvlist")
        self.btn_nvlist_clear = QtWidgets.QPushButton(self.groupBox_nvlist)
        self.btn_nvlist_clear.setGeometry(QtCore.QRect(10, 290, 41, 23))
        self.btn_nvlist_clear.setObjectName("btn_nvlist_clear")
        self.btn_nvlist_del = QtWidgets.QPushButton(self.groupBox_nvlist)
        self.btn_nvlist_del.setGeometry(QtCore.QRect(50, 290, 41, 23))
        self.btn_nvlist_del.setObjectName("btn_nvlist_del")
        self.btn_nvlist_add = QtWidgets.QPushButton(self.groupBox_nvlist)
        self.btn_nvlist_add.setGeometry(QtCore.QRect(210, 290, 41, 23))
        self.btn_nvlist_add.setCheckable(True)
        self.btn_nvlist_add.setObjectName("btn_nvlist_add")
        self.btn_nvlist_save = QtWidgets.QPushButton(self.groupBox_nvlist)
        self.btn_nvlist_save.setGeometry(QtCore.QRect(50, 320, 41, 23))
        self.btn_nvlist_save.setObjectName("btn_nvlist_save")
        self.table_nvlist = QtWidgets.QTableWidget(self.groupBox_nvlist)
        self.table_nvlist.setGeometry(QtCore.QRect(10, 20, 241, 261))
        self.table_nvlist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_nvlist.setObjectName("table_nvlist")
        self.table_nvlist.setColumnCount(0)
        self.table_nvlist.setRowCount(0)
        self.table_nvlist.horizontalHeader().setDefaultSectionSize(50)
        self.table_nvlist.verticalHeader().setDefaultSectionSize(20)
        self.table_nvlist.verticalHeader().setMinimumSectionSize(20)
        self.btn_nvlist_load = QtWidgets.QPushButton(self.groupBox_nvlist)
        self.btn_nvlist_load.setGeometry(QtCore.QRect(10, 320, 41, 23))
        self.btn_nvlist_load.setObjectName("btn_nvlist_load")
        self.btn_nvlist_shift = QtWidgets.QPushButton(self.groupBox_nvlist)
        self.btn_nvlist_shift.setGeometry(QtCore.QRect(170, 290, 41, 23))
        self.btn_nvlist_shift.setCheckable(True)
        self.btn_nvlist_shift.setObjectName("btn_nvlist_shift")
        self.btn_nvlist_get_tracker_pos = QtWidgets.QPushButton(self.groupBox_nvlist)
        self.btn_nvlist_get_tracker_pos.setGeometry(QtCore.QRect(170, 320, 81, 23))
        self.btn_nvlist_get_tracker_pos.setObjectName("btn_nvlist_get_tracker_pos")
        self.groupBox_nvlist_scripts = QtWidgets.QGroupBox(Form)
        self.groupBox_nvlist_scripts.setGeometry(QtCore.QRect(280, 270, 201, 91))
        self.groupBox_nvlist_scripts.setObjectName("groupBox_nvlist_scripts")
        self.list_nvlist_scripts = QtWidgets.QListWidget(self.groupBox_nvlist_scripts)
        self.list_nvlist_scripts.setGeometry(QtCore.QRect(10, 20, 161, 61))
        self.list_nvlist_scripts.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.list_nvlist_scripts.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.list_nvlist_scripts.setViewMode(QtWidgets.QListView.ListMode)
        self.list_nvlist_scripts.setObjectName("list_nvlist_scripts")
        self.btn_nvlist_scripts_del = QtWidgets.QPushButton(self.groupBox_nvlist_scripts)
        self.btn_nvlist_scripts_del.setGeometry(QtCore.QRect(170, 40, 21, 21))
        self.btn_nvlist_scripts_del.setObjectName("btn_nvlist_scripts_del")
        self.btn_nvlist_scripts_clear = QtWidgets.QPushButton(self.groupBox_nvlist_scripts)
        self.btn_nvlist_scripts_clear.setGeometry(QtCore.QRect(170, 60, 21, 21))
        self.btn_nvlist_scripts_clear.setObjectName("btn_nvlist_scripts_clear")
        self.btn_nvlist_scripts_add = QtWidgets.QPushButton(self.groupBox_nvlist_scripts)
        self.btn_nvlist_scripts_add.setGeometry(QtCore.QRect(170, 20, 21, 21))
        self.btn_nvlist_scripts_add.setObjectName("btn_nvlist_scripts_add")
        self.int_nvlist_numtrack = QtWidgets.QSpinBox(Form)
        self.int_nvlist_numtrack.setGeometry(QtCore.QRect(300, 50, 31, 21))
        self.int_nvlist_numtrack.setProperty("value", 2)
        self.int_nvlist_numtrack.setObjectName("int_nvlist_numtrack")
        self.chkbx_nvlist_localshift = QtWidgets.QCheckBox(Form)
        self.chkbx_nvlist_localshift.setGeometry(QtCore.QRect(290, 70, 71, 17))
        self.chkbx_nvlist_localshift.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbx_nvlist_localshift.setChecked(False)
        self.chkbx_nvlist_localshift.setObjectName("chkbx_nvlist_localshift")
        self.groupBox_nvlist_calscripts = QtWidgets.QGroupBox(Form)
        self.groupBox_nvlist_calscripts.setGeometry(QtCore.QRect(280, 180, 201, 91))
        self.groupBox_nvlist_calscripts.setObjectName("groupBox_nvlist_calscripts")
        self.list_nvlist_calscripts = QtWidgets.QListWidget(self.groupBox_nvlist_calscripts)
        self.list_nvlist_calscripts.setGeometry(QtCore.QRect(10, 20, 161, 61))
        self.list_nvlist_calscripts.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.list_nvlist_calscripts.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.list_nvlist_calscripts.setViewMode(QtWidgets.QListView.ListMode)
        self.list_nvlist_calscripts.setObjectName("list_nvlist_calscripts")
        self.btn_nvlist_calscripts_del = QtWidgets.QPushButton(self.groupBox_nvlist_calscripts)
        self.btn_nvlist_calscripts_del.setGeometry(QtCore.QRect(170, 40, 21, 21))
        self.btn_nvlist_calscripts_del.setObjectName("btn_nvlist_calscripts_del")
        self.btn_nvlist_calscripts_add = QtWidgets.QPushButton(self.groupBox_nvlist_calscripts)
        self.btn_nvlist_calscripts_add.setGeometry(QtCore.QRect(170, 20, 21, 21))
        self.btn_nvlist_calscripts_add.setObjectName("btn_nvlist_calscripts_add")
        self.btn_nvlist_calscripts_clear = QtWidgets.QPushButton(self.groupBox_nvlist_calscripts)
        self.btn_nvlist_calscripts_clear.setGeometry(QtCore.QRect(170, 60, 21, 21))
        self.btn_nvlist_calscripts_clear.setObjectName("btn_nvlist_calscripts_clear")
        self.label_nvlist_numtrack = QtWidgets.QLabel(Form)
        self.label_nvlist_numtrack.setGeometry(QtCore.QRect(280, 50, 21, 20))
        self.label_nvlist_numtrack.setObjectName("label_nvlist_numtrack")
        self.int_nvlist_caltime = QtWidgets.QSpinBox(Form)
        self.int_nvlist_caltime.setGeometry(QtCore.QRect(430, 70, 51, 21))
        self.int_nvlist_caltime.setMaximum(100000)
        self.int_nvlist_caltime.setSingleStep(5)
        self.int_nvlist_caltime.setProperty("value", 2)
        self.int_nvlist_caltime.setObjectName("int_nvlist_caltime")
        self.label_nvlist_caltime = QtWidgets.QLabel(Form)
        self.label_nvlist_caltime.setGeometry(QtCore.QRect(360, 70, 71, 20))
        self.label_nvlist_caltime.setObjectName("label_nvlist_caltime")
        self.chkbx_nvlist_enable = QtWidgets.QCheckBox(Form)
        self.chkbx_nvlist_enable.setGeometry(QtCore.QRect(360, 50, 111, 20))
        self.chkbx_nvlist_enable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbx_nvlist_enable.setChecked(False)
        self.chkbx_nvlist_enable.setObjectName("chkbx_nvlist_enable")
        self.groupBox_nvlist_auto = QtWidgets.QGroupBox(Form)
        self.groupBox_nvlist_auto.setGeometry(QtCore.QRect(280, 100, 201, 81))
        self.groupBox_nvlist_auto.setTitle("")
        self.groupBox_nvlist_auto.setObjectName("groupBox_nvlist_auto")
        self.btn_nvlist_auto_make_batch = QtWidgets.QPushButton(self.groupBox_nvlist_auto)
        self.btn_nvlist_auto_make_batch.setGeometry(QtCore.QRect(140, 20, 51, 51))
        self.btn_nvlist_auto_make_batch.setCheckable(True)
        self.btn_nvlist_auto_make_batch.setObjectName("btn_nvlist_auto_make_batch")
        self.dbl_nvlist_make_batch_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_nvlist_auto)
        self.dbl_nvlist_make_batch_threshold.setGeometry(QtCore.QRect(90, 0, 41, 20))
        self.dbl_nvlist_make_batch_threshold.setDecimals(0)
        self.dbl_nvlist_make_batch_threshold.setMaximum(1000.0)
        self.dbl_nvlist_make_batch_threshold.setSingleStep(1.0)
        self.dbl_nvlist_make_batch_threshold.setProperty("value", 15.0)
        self.dbl_nvlist_make_batch_threshold.setObjectName("dbl_nvlist_make_batch_threshold")
        self.Threshold = QtWidgets.QLabel(self.groupBox_nvlist_auto)
        self.Threshold.setGeometry(QtCore.QRect(10, 0, 81, 20))
        self.Threshold.setObjectName("Threshold")
        self.Min_sigma = QtWidgets.QLabel(self.groupBox_nvlist_auto)
        self.Min_sigma.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.Min_sigma.setObjectName("Min_sigma")
        self.dbl_nvlist_make_batch_min_sigma = QtWidgets.QDoubleSpinBox(self.groupBox_nvlist_auto)
        self.dbl_nvlist_make_batch_min_sigma.setGeometry(QtCore.QRect(90, 20, 41, 20))
        self.dbl_nvlist_make_batch_min_sigma.setDecimals(1)
        self.dbl_nvlist_make_batch_min_sigma.setMaximum(100.0)
        self.dbl_nvlist_make_batch_min_sigma.setSingleStep(0.1)
        self.dbl_nvlist_make_batch_min_sigma.setProperty("value", 2.0)
        self.dbl_nvlist_make_batch_min_sigma.setObjectName("dbl_nvlist_make_batch_min_sigma")
        self.Max_sigma = QtWidgets.QLabel(self.groupBox_nvlist_auto)
        self.Max_sigma.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.Max_sigma.setObjectName("Max_sigma")
        self.dbl_nvlist_make_batch_max_sigma = QtWidgets.QDoubleSpinBox(self.groupBox_nvlist_auto)
        self.dbl_nvlist_make_batch_max_sigma.setGeometry(QtCore.QRect(90, 40, 41, 20))
        self.dbl_nvlist_make_batch_max_sigma.setDecimals(1)
        self.dbl_nvlist_make_batch_max_sigma.setMaximum(100.0)
        self.dbl_nvlist_make_batch_max_sigma.setSingleStep(0.1)
        self.dbl_nvlist_make_batch_max_sigma.setProperty("value", 5.0)
        self.dbl_nvlist_make_batch_max_sigma.setObjectName("dbl_nvlist_make_batch_max_sigma")
        self.dbl_nvlist_make_batch_overlap = QtWidgets.QDoubleSpinBox(self.groupBox_nvlist_auto)
        self.dbl_nvlist_make_batch_overlap.setGeometry(QtCore.QRect(90, 60, 41, 20))
        self.dbl_nvlist_make_batch_overlap.setDecimals(1)
        self.dbl_nvlist_make_batch_overlap.setMaximum(1.0)
        self.dbl_nvlist_make_batch_overlap.setSingleStep(0.1)
        self.dbl_nvlist_make_batch_overlap.setProperty("value", 0.5)
        self.dbl_nvlist_make_batch_overlap.setObjectName("dbl_nvlist_make_batch_overlap")
        self.Overlap = QtWidgets.QLabel(self.groupBox_nvlist_auto)
        self.Overlap.setGeometry(QtCore.QRect(10, 60, 81, 20))
        self.Overlap.setObjectName("Overlap")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.table_nvlist, self.btn_nvlist_add)
        Form.setTabOrder(self.btn_nvlist_add, self.btn_nvlist_shift)
        Form.setTabOrder(self.btn_nvlist_shift, self.btn_nvlist_clear)
        Form.setTabOrder(self.btn_nvlist_clear, self.btn_nvlist_del)
        Form.setTabOrder(self.btn_nvlist_del, self.btn_nvlist_load)
        Form.setTabOrder(self.btn_nvlist_load, self.btn_nvlist_save)
        Form.setTabOrder(self.btn_nvlist_save, self.btn_nvlist_get_tracker_pos)
        Form.setTabOrder(self.btn_nvlist_get_tracker_pos, self.int_nvlist_numtrack)
        Form.setTabOrder(self.int_nvlist_numtrack, self.btn_nvlist_drive)
        Form.setTabOrder(self.btn_nvlist_drive, self.chkbx_nvlist_localshift)
        Form.setTabOrder(self.chkbx_nvlist_localshift, self.btn_nvlist_start)
        Form.setTabOrder(self.btn_nvlist_start, self.btn_nvlist_stop)
        Form.setTabOrder(self.btn_nvlist_stop, self.int_nvlist_caltime)
        Form.setTabOrder(self.int_nvlist_caltime, self.list_nvlist_calscripts)
        Form.setTabOrder(self.list_nvlist_calscripts, self.btn_nvlist_calscripts_add)
        Form.setTabOrder(self.btn_nvlist_calscripts_add, self.btn_nvlist_calscripts_del)
        Form.setTabOrder(self.btn_nvlist_calscripts_del, self.btn_nvlist_calscripts_clear)
        Form.setTabOrder(self.btn_nvlist_calscripts_clear, self.list_nvlist_scripts)
        Form.setTabOrder(self.list_nvlist_scripts, self.btn_nvlist_scripts_add)
        Form.setTabOrder(self.btn_nvlist_scripts_add, self.btn_nvlist_scripts_del)
        Form.setTabOrder(self.btn_nvlist_scripts_del, self.btn_nvlist_scripts_clear)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Batch Control"))
        self.btn_nvlist_stop.setText(_translate("Form", "Stop"))
        self.btn_nvlist_drive.setText(_translate("Form", "drive"))
        self.btn_nvlist_start.setText(_translate("Form", "Run"))
        self.groupBox_nvlist.setTitle(_translate("Form", "NV List"))
        self.btn_nvlist_clear.setText(_translate("Form", "clear"))
        self.btn_nvlist_del.setText(_translate("Form", "delete"))
        self.btn_nvlist_add.setText(_translate("Form", "add"))
        self.btn_nvlist_save.setText(_translate("Form", "save"))
        self.btn_nvlist_load.setText(_translate("Form", "load"))
        self.btn_nvlist_shift.setText(_translate("Form", "shift"))
        self.btn_nvlist_get_tracker_pos.setText(_translate("Form", "get tracker pos"))
        self.groupBox_nvlist_scripts.setTitle(_translate("Form", "Experiment Scripts"))
        self.btn_nvlist_scripts_del.setText(_translate("Form", "-"))
        self.btn_nvlist_scripts_clear.setText(_translate("Form", "x"))
        self.btn_nvlist_scripts_add.setText(_translate("Form", "+"))
        self.chkbx_nvlist_localshift.setText(_translate("Form", "local"))
        self.groupBox_nvlist_calscripts.setTitle(_translate("Form", "Calibration Scripts"))
        self.btn_nvlist_calscripts_del.setText(_translate("Form", "-"))
        self.btn_nvlist_calscripts_add.setText(_translate("Form", "+"))
        self.btn_nvlist_calscripts_clear.setText(_translate("Form", "x"))
        self.label_nvlist_numtrack.setText(_translate("Form", "track"))
        self.label_nvlist_caltime.setText(_translate("Form", "Cal time (min)"))
        self.chkbx_nvlist_enable.setText(_translate("Form", "Use NV List"))
        self.btn_nvlist_auto_make_batch.setText(_translate("Form", "auto \n"
"make \n"
"batch"))
        self.Threshold.setText(_translate("Form", "Threshold(kcps)"))
        self.Min_sigma.setText(_translate("Form", "Min sigma"))
        self.Max_sigma.setText(_translate("Form", "Max sigma"))
        self.Overlap.setText(_translate("Form", "Overlap"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

